### ISSUE TITLE
Consider defaulting to ".dev"

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#10]
...I would expect that anyone installing this would want to replace pow rather than run alongside, and if running alongside that would be the non-default case.

It's fine if you just want to close this, but I think the generic `.dev` is cleaner than `pdev` which reveals a bit about the mechanics. Feels like `pdev` should be the compatibility mode and `dev` should be the default.

<3 <3 <3 

😄

**Comment by evanphx** [comment]
@sstephenson How do you feel about this? I explicitly didn't want to stop on peoples pow installations, that's why I defaulted to `pdev` right now.

**Comment by sstephenson** [comment]
I don’t have a problem with puma-dev taking over the `.dev` domain. However, you should know that Google bought the rights to `.dev` in 2015, and all public queries on that TLD now return 127.0.53.53.

Going forward, I think it’d be best to use a top-level domain that will explicitly never be allocated for public use. [RFC 2606](https://tools.ietf.org/html/rfc2606#section-2) reserves `.test`, `.example`, `.invalid`, and `.localhost` for testing purposes. Of those, I like `.test` the best.

**Comment by evanphx** [comment]
Hm, what about using an actual global domain that we point to 127.0.0.1.
That would simplify installation too. 'dev.sh' is taken but something like
that?

**Comment by paulca** [comment]
I was getting a few requests resolving to 127.0.53.53 and couldn't understand why. That explains that.

@evanphx  `dev.sh` or similar would work of course, but then apps in development would require their `tld_length` configuration to be set in development mode, even when their production app was running on TLD with just one part.

**Comment by evanphx** [comment]
Is `tld_length` a rails configuration thing? Puma-dev can pretty easily detect requests for `x.dev.sh` and send them to the app. I'm not sure what the issue would be.

**Comment by paulca** [comment]
@evanphx Yeah, without setting the `tld_length`, things like subdomain route constraints and any code that relied on `request.domain` or `request.subdomain` would need to be managed, basically requiring a different setup in development mode than production.
