### ISSUE TITLE
When unable to boot app show error details instead of "unexpected exit"

### ISSUE THREAD

**Issue by espen** [puma/puma-dev#100]
Currently if Rails is unable to boot Puma just displays "unexpected exit". The first time I encountered this I assumed there was something wrong with Puma and tried to restart it and debug Puma instead of my app. It would be nice to see the same error as when trying to start the Rails app in a console.

**Comment by andyroberts** [comment]
This just happened to me. Check `~/Library/Logs/puma-dev.log`. In my case it was complaining that the puma gem itself was missing. I added puma to the developer group of my Gemfile and ran bundle install and all was fine*.

* Well, technically, it wouldn't install at first because I had recently upgraded OSX and the command-line tools weren't installed. `xcode-select --install` sorted that, then the puma gem could be installed.

**Comment by concept47** [comment]
Usually I'll just run the `puma` command in the directory, and the error gets spit out, but yes this would be an improvement

**Comment by tadman** [comment]
Adding the `gem 'puma'` directive to `Gemfile` fixes this, but that message really could be a lot more informative.

Considering how descriptive the messages Rails generates are becoming, Puma should at least give a hint here.

**Comment by Petercopter** [comment]
This happened to me because I have Webpacker installed, and my packages didn't match. Thanks to the tip from @concept47, I was able to diagnose and resolve the problem quickly.
```
$ puma
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development


========================================
  Your Yarn packages are out of date!
  Please run `yarn install` to update.
========================================


To disable this check, please add `config.webpacker.check_yarn_integrity = false`
to your Rails development config file (config/environments/development.rb).


yarn check v1.7.0
warning Integrity check: Top level patterns don't match
error Integrity check failed
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.


! Unable to load application: SystemExit: exit
```

**Comment by evanphx** [comment]
Agreed, it needs to report better output when the app won't start up.
