### ISSUE TITLE
Apps not loading [Manjaro - linux]

### ISSUE THREAD

**Issue by ricbermo** [puma/puma-dev#103]
Hi there,

I installed the tool and dev-tld-resolver on manjaro, an archlinux based distro. Pinging to test.dev does return 100% packages received. Linking the app with `./puma-dev link .` does create a symlink in `~./puma-dev` directory but the app is not loading in my browser.

I've also tried running puma-dev in background.

Am I missing something?

Thanks

**Comment by kaizencodes** [comment]
Same situation on Ubuntu 16.04 LTS

**Comment by picandocodigo** [comment]
This seems to be still happening with Ubuntu 16.04, `dev-tld-resolver` and `puma-dev`. Will update if I find a workaround.

**Comment by gabriel-cardoso** [comment]
Got stuck for a few hours when I realized I had to install the `puma` gem

```
gem install puma
```

**Comment by ricbermo** [comment]
I'm closing this since I'm not using it anymore.
