### ISSUE TITLE
Start app in attachable terminal

### ISSUE THREAD

**Issue by joallard** [puma/puma-dev#104]
This is a wishlist enhancement.

Sometimes I want to debug something in my Rails apps using Pry. I wish I could open an terminal and bind to the app that Puma-dev is running so I could interact with the server process.

**Comment by danielwestendorf** [comment]
Try pry-remote. https://github.com/mon-ouie/pry-remote

**Comment by evanphx** [comment]
I'll consider it, but it's super complicated!
