### ISSUE TITLE
puma-dev should support more than just Ruby

### ISSUE THREAD

**Issue by fd** [puma/puma-dev#108]
There are many dev servers (a reverse proxy + `.dev` DNS resolver) out there. Most of these support just a single PL. This is obviously not ideal as there is nothing PL specific about a reverse proxy or a `.dev` DNS resolver.

I think puma-dev should not just support ruby apps (and generic http servers via a _proxy entry_).

There are many defacto standards for describing how to run a HTTP server (`Procfile`, `docker-compose.yaml`, npm's `package.json`, etc...) and it would be great if puma-dev would support these too.

Each of these _backends_ could be isolated in a separate _driver_ package. Below you an find a first draft of the interface a driver would need to implement.

```go
type Config struct {
	Path    string // Path to entry in ~/.puma-dev
	Environ []string
	Stdin   io.Writer
	Stdout  io.Reader
	Stderr  io.Reader
}

type Driver interface {
	Name() string                          // Name of the driver
	Detect(path string) bool               // Detect if the driver is supported
	Create(config Config) (Backend, error) // Create a backend with Config
}

type Backend interface {
	// ServeHTTP a request (the backend is responsible for dispatching the actual request)
	ServeHTTP(w http.ResponseWriter, r *http.Request)

	// Process associated with the backend if any.
	// This is allowed to  be nil when the driver doesn't use backend processes (eg. a simple proxy)
	Process() exec.Command
}
```

**Comment by nacengineer** [comment]
isn't this why nginx and apache exist? seems like YAGNI to use puma-dev for non ruby applications

**Comment by Rishka** [comment]
Not really, nginx/apache won't start your other "backend" for you. An example could be `webpack-dev-server`. Currently you can assign the port to `puma-dev`, but in this case, `puma-dev` could start your web pack for you.

**Comment by MikeRogers0** [comment]
> you're on OS X and maybe these are a bit harder to setup

`puma-dev` has been an amazing timesaver when it comes to avoiding a lot of setup, it would be great to use alongside something like `docker-compose`.

I might be a bit naive, but if puma-dev could look for a file such as `.puma-dev` in a project root, then around https://github.com/puma/puma-dev/blob/master/dev/app.go#L254 execute its contents instead of `exec puma -C $CONFIG`, would that achieve the same effect?

**Comment by evanphx** [comment]
Hm, being able to run docker-compose is quite interesting. I'll have to noodle on that.

**Comment by gee-forr** [comment]
@MikeRogers0 - in the meantime, don't symlink your app, but just write the exposed port into your puma-dev file. i.e.

```shell
cat ~/.puma-dev/my-app

8080
```

If you're exposing TCP 8080 as your port, puma-dev will proxy it, and you should be able to go to https://my-app.dev normally.

Also take a look at using a `docker-compose.override.yml` file to set dev environment specific settings like the ports thing above, which you probably don't wanna do in prod.

Hope this helps.

**Comment by subvertallchris** [comment]
@gee-forr That's such a great tip and it works perfectly, I'd never have figured that out on my own. Is that in the docs somewhere?
