### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by sachse** [puma/puma-dev#11]
Pow supported loading a config file which was super handy for people using a Ruby version manager like chruby. It let you do something like the following to make sure the server was using the right version of Ruby.

```sh
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby $(cat ~/.ruby-version)
```

Pretty simple stuff but very, very helpful.

**Comment by evanphx** [comment]
This is the same as #8 and I'm implementing it now!

**Comment by sachse** [comment]
Thanks Evan! However, Pow's .powconfig was a global config file that could be placed in $HOME and then worked for all Pow processes. What do you think about adding something like this to avoid having to duplicate configuration across projects?

**Comment by evanphx** [comment]
@sachse I just added support in 7b22ae7 for loading `.powconfig` as well. puma-dev won't use the `POW_*` variables but you can use it to add other variables.
