### ISSUE TITLE
Support port/domain configuration in env variables

### ISSUE THREAD

**Issue by while1malloc0** [puma/puma-dev#110]
It seems like a useful feature for puma-dev would be the ability to read http port, domain, etc. configuration values from environment variables. This would help ease the transition from pow for those of us who used the POW_* environment variables to configure our apps. I noticed that https://github.com/puma/puma-dev/issues/11 added the ability to read from a .powconfig file, but explicitly skips support for reading the POW_* variables. Would the ability to configure something like PUMA_DEV_HTTP_PORT be outside of the intended use cases for this app? I'm happy to submit a PR for this, assuming that it's not already supported and it's a feature that others would find useful.

**Comment by evanphx** [comment]
Sure, happy to look at that PR!
