### ISSUE TITLE
How do you stop, start, restart on OS X?

### ISSUE THREAD

**Issue by kieraneglin** [puma/puma-dev#111]
I'm not a Unix guru and I really can't find anything on the matter! 

Thank you

**Comment by danielwestendorf** [comment]
From Terminal.app type: `pkill -USR1 puma-dev`

**Comment by kieraneglin** [comment]
Thank you!  Weird that there's no baked-in stop and restart command

**Comment by concept47** [comment]
on osx this didn't seem to work for me, because puma-dev is in the /Library/LaunchAgents directory it kept trying to restart over and over and over.

What I found worked was loading and unloading the plist 
`launchctl unload /Users/<your username>/Library/LaunchAgents/io.puma.dev.plist`
`launchctl load /Users/<your username>/Library/LaunchAgents/io.puma.dev.plist`

**Comment by morgler** [comment]
The README said something about a convenient `puma-dev -stop` command – but this is not working. I would appreciate to have a simple way off stopping and starting puma-dev from time to time (e.g. when having having to do `rake db:drop` on a branch). It would be awesome, if you could add such a command!

**Comment by morgler** [comment]
Oh, I see: last release (0.10) was about a year ago – so this change is not yet released :(. Could you please create a new release that corresponds with the documentation in the README?

**Comment by evanphx** [comment]
So sorry about the delay, new version out now.

**Comment by fiedl** [comment]
Works like charm, thanks for the release!

Summary for later reference:

```
# Update to the current version of puma-dev.
brew upgrade puma-dev

# Kill the current puma-dev instances. They will be restarted when accessed through the browser.
puma-dev -stop
```

**Comment by jgervin** [comment]
This doesn't seem to be fixed. I am tyring pkill -USR1 puma-dev and puma-dev -stop and the server restarts instantly.

**Comment by ivellios** [comment]
I have the same issue. It just keeps showing up. And it uses my port 80 which I need to use. How do I kill it permanently? Or just remove permanently? `-uninstall` does not work either.

**Comment by chrishough** [comment]
This has not been, I am experiencing the same problem. How do you stop this?

**Comment by nateberkopec** [comment]
People coming to this issue from Google:

To restart Puma: $ pkill -USR1 puma-dev
To stop: $ puma-dev -stop
