### ISSUE TITLE
running puma-dev install silently wipes out previous plist settings on OSX

### ISSUE THREAD

**Issue by concept47** [puma/puma-dev#112]
This bit me today, and had me chasing my tail for a couple of hours to figure out how I broke everything :D

say you run 

`puma-dev -install -http-port 81`

because you have Apache or Nginx running on port 80, then promptly forget and want to configure the puma-dev idle time so you run

`puma-dev -install -timeout 180m`

This will reset http-port in your plist file to 80. OS X will promptly reload the plist and start failing as it tries to restart every 10 seconds, with errors in the puma log that look like

`Error listening: accept tcp 0.0.0.0:0: accept: invalid argument`

and in the OSX system log as

`io.puma.dev[1616]): Service exited with abnormal code: 1
Service only ran for 0 seconds. Pushing respawn out by 10 seconds`

If you're unfortunate enough to have installed puma-dev a while ago, it might take the user a while to track down and fix the problem. 

What I suggest should happen to avoid this is that the already configured settings should not be reset unless explicitly passed in as a flag to the install command.

**Comment by evanphx** [comment]
I'm not sure how to solve that because if it were to honor the existing settings, I'd get the opposite issue openned, that it doesn't honor the settings on the command line.
