### ISSUE TITLE
Request subdomain with xip.io

### ISSUE THREAD

**Issue by thomey** [puma/puma-dev#114]
Thanks for a great project 👍 , and also for having xip.io support.

When you try to use a subdomain with xip.io, e.g. `subdomain.app_name.A.B.C.D.xip.io`, puma-dev correctly routes the request to the intended (Rails) app, but the request object subdomain becomes `subdomain.app_name.A.B.C.D` instead of just the expected `subdomain`. Would be nice to have correct subdomain support closer to production setup, so we don't have to use regexp etc. for routing constraints.

Is this something that puma-dev could support?

**Comment by nashbridges** [comment]
@thomey have a look at https://github.com/fphilipe/xipio/

**Comment by thomey** [comment]
@nashbridges Thanks, that seems better than the regexp approach since it only affects development mode. Closing.
