### ISSUE TITLE
Sierra: cant install resolver in background

### ISSUE THREAD

**Issue by bjensen** [puma/puma-dev#118]
I use to use pow but I used the uninstaller and followed the script manually.
On my sierra I installed it using homebrew and did a su puma-dev -setup and puma-dev -install.

```
telnet localhost 9253
Trying ::1...
telnet: connect to address ::1: Connection refused
```

For debugging I inserted the contents of the LaunchAgent into the command line:
```
 /usr/local/Cellar/puma-dev/0.10/bin/puma-dev -launchd -dir ~/.puma-dev -d dev -timeout 15m0s
* Directory for apps: /Users/brianj/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: inherited from launchd
* HTTPS Server port: inherited from launchd
! Puma dev listening on http and https
2017/05/18 20:14:18 Error listening: couldn't activate launchd socket Socket
```

If I start puma-dev in the foreground it works fine on port 9280 with http.

**Comment by rodrigopinto** [comment]
I have the same issue here. I've searched around the web and no solution to it.

**Comment by aarongray** [comment]
+1 on this issue.

**Comment by Van-Ausburn** [comment]
sudo -E puma-dev -http-port 80 -https-port 443

**Comment by MartianLee** [comment]
I have same problem too. I can't find process "ps aux | grep puma-dev" after install. plz help T.T

**Comment by konung** [comment]
In my case, while I was getting this error, the issue was related to `yarn` not working after I updated brew packages and also updated to High Sierra 10.13.4 ( one of the libraries that yarn depend on was removed by another package". Reinstalling yarn and rerunning it in my Rails app folder to install packages, fixed it. 

```
brew remove yarn
brew install yarn
yarn install
```
fixed the issue for me

**Comment by MartianLee** [comment]
Thanx for kind comment. I found that some problem from yarn or other basic library is not upgraded. so I reinstalled all other things and I fixed it. Thank you for your help.
