### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kieraneglin** [puma/puma-dev#121]
Not to be rude, but I'm getting the impression that this project is no longer being worked on. Issues are being closed, but no commits or PR responses for 7 months makes me think it's not active. 

Is this the case?  Thank you!

**Comment by olivierlacan** [comment]
7 months might be a little quick to start asking if this project's dead. 😉 

If you have a bug that needs to be fixed by a new release or a PR you can't wait to get merged, why don't you reach out to the maintainer to see if they have some time to merge it?

**Comment by bjensen** [comment]
I think its a valid question since the list of unclosed issues piling up..

**Comment by evanphx** [comment]
Not dead yet! Just a side project so I don't always keep up on it as much as I'd like. Doing a sweep of things now.

**Comment by lleolin** [comment]
It's great that you merged in the PRs, but, with all due respect, it doesn't really do us users any good if there's no release containing the fixes.

**Comment by evanphx** [comment]
@lleolin Totally valid, I'll get a release out this week. Sorry for the delay.

**Comment by bjensen** [comment]
Still no release?
