### ISSUE TITLE
Error: `getent: executable file not found in $PATH`

### ISSUE THREAD

**Issue by adamcrown** [puma/puma-dev#122]
I'm running Sierra 10.12.5 and got this following error in my `~/Library/Logs/puma-dev.log`

```shell
getent: executable file not found in $PATH
```

It seems like the error is raised on [this line](https://github.com/puma/puma-dev/blob/80d569425853b7aaf10a91b47513fa7d80d67741/homedir/homedir.go#L150) which only gets hit if `$HOME` isn't defined. So I just added the following lines to `~/Library/LaunchAgents/io.puma.dev.plist` which seems to have fixed it, but obviously is just a hackey workaround.

```xml
<key>EnvironmentVariables</key>
<dict>
  <key>HOME</key>
  <string>/Users/my_username</string>
</dict>
```

It would be great to have a fix for this, but at least I hope it will help somebody else with this problem.

**Comment by nonrational** [comment]
`getent` isn't available on macOS, so that fallback isn't cross-platform valid. still, i'm flummoxed as to how you managed to run puma-dev in an environment without $HOME set. 🤔

**Comment by nonrational** [comment]
Actually, `getent` doesn't exist in the darwin branch of `puma-dev/homedir`. So, the error is actually higher up. Somehow, `runtime` didn't recognize your system as Darwin.

https://github.com/puma/puma-dev/blob/8907643a169565e11951e8ed0e425453108dcf56/homedir/homedir.go#L45-L52
