### ISSUE TITLE
Does Puma-dev support Rails' webpack integration?

### ISSUE THREAD

**Issue by jeromedalbert** [puma/puma-dev#123]
Puma-dev supports Rails 5.0's new ActionCable feature. Does it support Rails 5.1's new Webpack integration through Webpacker?

Any rack app works, but webpack is a Node process, so I guess it's not supported. I am wondering if there is a workaround to support webpacker. Or maybe support Procfile apps that do not necessarily have rack-only processes (out of this project's scope?).

**Comment by tylerhunt** [comment]
I've been using Webpacker with Puma-dev by running `webpack` in watch mode (`./bin/webpack --watch --progress`). This will continually update the webpacker assets in `public/packs`, so they can then be served by Rails through the existing Puma-dev process.

If you want to run `webpack-dev-server` instead, presumably you could start that process and map the port to a Puma-dev hostname (e.g. `assets.myapp.dev`). You'll run into issues here if you're working on multiple apps simultaneously, as you'll have to mange the port number each uses, shuffle around which host is mapped to the default port, or use a generic mapping across all the apps and spin up and down the asset server as needed.

@jeromedalbert Did you have an integration in mind beyond these two options?

**Comment by jeromedalbert** [comment]
@tylerhunt Thanks, I think the second option is what I am looking for, my idea being "launch all the servers automatically so that I don't fiddle with them". Although the manual port number management is not ideal. I may try it out and see if it works for my needs.

I guess another alternative for automatic port management is using Foreman and Procfiles with $PORT, but then I lose the ease of having `.dev` domains and zero-config https support.

I guess there is no easy solution for my need then! #1stWorldProblems
