### ISSUE TITLE
puma-dev -stop: flag provided but not defined: -stop

### ISSUE THREAD

**Issue by ileitch** [puma/puma-dev#125]
The README states `puma-dev -stop` can be used to stop, however it produces the error:
```
flag provided but not defined: -stop
```

followed by the usage.

Using version v0.10 installed via homebrew on macOS 10.12.6.

**Comment by 3wille** [comment]
``-stop`` is not available in ``v0.10``. If you checkout the tag ``v0.10`` you can see that ``-stop`` is not yet documented.

**Comment by TangRufus** [comment]
How far are we from the next release?

**Comment by manuelmeurer** [comment]
Could we please fix this?

**Comment by evanphx** [comment]
So sorry about the delay v0.11 is out with these fixes.

**Comment by manuelmeurer** [comment]
No need to apologize... thanks for your work on this, puma-dev is fantastic! 💯
