### ISSUE TITLE
Chrome to force .dev domains to HTTPS via preloaded HSTS

### ISSUE THREAD

**Issue by adambutler** [puma/puma-dev#127]
Details at https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by moyashipan** [comment]
similar issue: #36

**Comment by concept47** [comment]
@evanphx any updates on this one? Google Chrome updated and now I can't navigate to .dev domains at all.

**Comment by cseebach-lh** [comment]
As a workaround, I've been using `-d test` when I run puma-dev.

**Comment by wjp2013** [comment]
use `.localhost` 
read this. https://tools.ietf.org/html/rfc2606

**Comment by nratter** [comment]
remove the file `/etc/resolver/dev` and then `puma-dev -stop`

**Comment by nonrational** [comment]
using raw `dev` as a TLD is now discouraged. we're using `test` by default in recent versions.
