### ISSUE TITLE
Instructions for developing and contributing to the project

### ISSUE THREAD

**Issue by RobinDaugherty** [puma/puma-dev#128]
I'm a Ruby developer and I'd like to help, but the biggest barrier is figuring out how to build the project from source.

Instead of giving instructions to _develop_ the project, the readme currently gives instructions to check out and build the latest version from github. If someone wants to work from a development clone of the project and actually contribute, those instructions are wrong/incomplete.

#94 tries to address this partially, because this step is missing if one tries to build from within a clone of the project. But the comment there seems to indicate that it should not be necessary.

I'm coming at this as a Go noob, but one with incentive to contribute to this project.

**Comment by evanphx** [comment]
If you clone this into $GOPATH/src/github.com/puma/puma-dev, then run `make` it will build it for ya.
