### ISSUE TITLE
Why zsh?

### ISSUE THREAD

**Issue by koenpunt** [puma/puma-dev#13]
I noticed zsh is the shell that is used. Couldn't be this just bash? Or even sh?

**Comment by evanphx** [comment]
That's a mistake, it should be the users shell there.

**Comment by koenpunt** [comment]
I've updated the plist to use `sh`, which works fine as well. I guess that would be a sensible default?

**Comment by evanphx** [comment]
Yeah, that will be the serial but it's important that the code see in the
SHELL env var is set and use it if so. That's because we want to be sure to
load the users normal setup to pickup things like rbenv
