### ISSUE TITLE
Running in foreground, can't bind to privileged ports (< 1024)

### ISSUE THREAD

**Issue by rlue** [puma/puma-dev#132]
I'm trying to run puma-dev as a foreground process so that it can be used in a foreman Procfile and its output displayed alongside that of other processes when launched with `foreman start`.

The following invocations of puma-dev

    $ puma-dev -install          # as a launchd service
    $ puma-dev                   # in foreground, listening for HTTPS on port 9283

both work fine, except that the former does not provide console output and the latter requires the port to be manually included in the URL (which would require the rewriting of path helpers used throughout our application).

Curiously, puma-dev does not seem to know when it has attempted to bind to a privileged port.

    $ puma-dev -https-port 443
    * Directory for apps: /Users/rlue/.puma-dev
    * Domains: dev
    * DNS Server port: 9253
    * HTTP Server port: 9280
    * HTTPS Server port: 443
    ! Puma dev listening on http and https

puma-dev starts up as normal, with no indication that it does not have permissions to bind to 443. Requests sent to the status API are rejected:

    $ curl -H "Host: puma-dev" localhost:443/events
    curl: (7) Failed to connect to localhost port 443: Connection refused

Appears unrelated to #66 (I've never used pow before, `sudo pfctl -F all` didn't do anything, and most notably, it _does_ work when run as a launchd service).

---

* Mac OS 10.11 El Capitan
* puma-dev v0.10 (go1.7)
* No firewall

**Comment by evanphx** [comment]
This is expected sadly. This is the normal unix permissions on low ports. It should report an error if it can't bind to the port, I'll have to look into that though.
