### ISSUE TITLE
App Killed At Startup: stdout/stderr closed

### ISSUE THREAD

**Issue by Undistraction** [puma/puma-dev#135]
I have installed puma-dev and set it up to run in the background using: `puma-dev -install`

I have a Rails application symlinked into `~/.puma-dev`.
```
ls ~/.puma-dev # tmp example
```
The Rails app runs fine on `https://localhost:3000` if I run `rails s -b 'ssl://localhost:3000?key=certificates/localhost.key&cert=certificates/localhost.crt'`.

However, according to the docs, puma-dev handles certificates itself.

I have a `.powrc` file in the root of my project which uses chruby to set the ruby version using a `.ruby-version` file also in the root:

```
source /usr/local/share/chruby/chruby.sh
chruby $(cat .ruby-version)
```

As far as I can see, this setup should be good to go, however if I hit `https://example.dev`, I get a page with the message:

> unexpected exit

If I run `tail -f ~/Library/Logs/puma-dev.log`:

```
! Booting app '.' on socket /Users/me/.puma-dev/example/tmp/puma-dev-372.sock
.[5005]: bash: no job control in this shell
.[5005]: bash: line 23: exec: puma: not found
! Killing '.' (5005)
* App '.' shutdown and cleaned up
! Detecting app '.' dying on start
! Booting app '.' on socket /Users/me/.puma-dev/example/tmp/puma-dev-372.sock
.[5262]: bash: no job control in this shell
.[5262]: bash: line 23: exec: puma: not found
! Killing '.' (5262)
* App '.' shutdown and cleaned up
! Detecting app '.' dying on start
```

If I run `curl -H "Host: puma-dev" localhost/events`:

```
{"time":"2017-11-02 13:54:19.482745269 +0000 GMT m=+58.680623399","event":"app_lookup","path":"/Users/me/.puma-dev/example"}
{"time":"2017-11-02 13:54:19.484556931 +0000 GMT m=+58.682435061","event":"booting_app","app":".","socket":"/Users/me/.puma-dev/example/tmp/puma-dev-372.sock"}
{"time":"2017-11-02 13:54:19.484592411 +0000 GMT m=+58.682470541","event":"waiting_on_app","app":"."}
{"time":"2017-11-02 13:54:20.443084271 +0000 GMT m=+59.640962401","event":"killing_app","app":".","pid":1215,"reason":"stdout/stderr closed"}
{"time":"2017-11-02 13:54:20.443139769 +0000 GMT m=+59.641017899","event":"shutdown","app":"."}
{"time":"2017-11-02 13:54:20.443151868 +0000 GMT m=+59.641029998","event":"lookup_error","error":"unexpected exit"}
{"time":"2017-11-02 13:54:20.443214526 +0000 GMT m=+59.641092656","event":"dying_on_start","app":"."}
{"time":"2017-11-02 13:54:20.961551142 +0000 GMT m=+60.159429272","event":"app_lookup","path":"/Users/me/.puma-dev/example"}
{"time":"2017-11-02 13:54:20.963015056 +0000 GMT m=+60.160893186","event":"booting_app","app":".","socket":"/Users/me/.puma-dev/example/tmp/puma-dev-372.sock"}
{"time":"2017-11-02 13:54:20.963049618 +0000 GMT m=+60.160927748","event":"waiting_on_app","app":"."}
{"time":"2017-11-02 13:54:21.91351876 +0000 GMT m=+61.111396890","event":"killing_app","app":".","pid":1473,"reason":"stdout/stderr closed"}
{"time":"2017-11-02 13:54:21.913564357 +0000 GMT m=+61.111442487","event":"shutdown","app":"."}
{"time":"2017-11-02 13:54:21.913574879 +0000 GMT m=+61.111453009","event":"lookup_error","error":"unexpected exit"}
{"time":"2017-11-02 13:54:21.91360559 +0000 GMT m=+61.111483720","event":"dying_on_start","app":"."}
```

My rails logs are empty, so it seems the application is never run.

I'm on OSX 10.11.6, running the latest version of puma-dev (0.11)

**Comment by shaicoleman** [comment]
I experienced a similar issue, it was caused by the dotenv gem that loaded a .env file that overrided the PATH variable

**Comment by ArthurN** [comment]
If you're coming from pow straight to puma-dev, you might also be missing an obvious step which is to install puma itself: `gem install puma`. ;-)

**Comment by jamieorc** [comment]
I just changed from Ruby 2.2.x to 2.3.x and have the same issue. RVM. If I switch back to 2.2.x, app runs fine.

**Comment by tonycchung** [comment]
ran into this myself, check your .powrc, .powenv, .powconfig in the app is sourcing chruby correctly.

typically:

```
  source /usr/local/share/chruby/chruby.sh
  chruby $(cat .ruby-version)
```

in my case, i use this:

```
if [ -f "/usr/local/share/chruby/chruby.sh" ]; then
  source /usr/local/share/chruby/chruby.sh
  chruby $(cat .ruby-version)
fi
```

as not all of my coworkers use chruby, there was a bug in my `if` that prevented chruby from being sourced.

**Comment by pmackay** [comment]
Just to add to this, have just got puma-dev working. I found I _had_ to have a `.powrc` file in my project root to get it to work, otherwise it was picking up the macOS system ruby and creating a mismatch between that and the ruby the project needed. Is there any way to ensure puma-dev gets the project ruby version _without_ each project needing a `.powrc` file? (just wondering, its not a big issue)

**Comment by benpetro** [comment]
I fixed this by creating my `.ruby-version` file directly in my rails app directory, not in a parent directory.

**Comment by h0jeZvgoxFepBQ2C** [comment]
This issue is still open, somehow I had to create a ```.powrc```file in my project with following content to get it running

```
if [ -f "$rvm_path/scripts/rvm" ]; then
  source "$rvm_path/scripts/rvm"
  rvm use .
fi
```

I have the same content in my ```~/.powconfig``` but it looks like it has been ignored.

**Comment by dbackeus** [comment]
Same thing happened to me today. I've been running `puma-dev` without issues for years but this morning all of a sudden all my puma apps were crashing with `bash: line 23: exec: puma: not found`. Respawning via `puma-dev -stop` nor rebooting Macbook helped. In my terminal `bundle exec puma` works just fine for all apps.

I use `rbenv` for ruby management so as a work-around adding a `.powrc` file including `eval "$(rbenv init -)"` "solved" the issue for me.

**Comment by vmsp** [comment]
I just installed `puma-dev` and am having the exact issue reported by @dbackeus.

Ruby: 2.7.2
Rails: 6.1.1
Puma: 5.2.1
