### ISSUE TITLE
Chrome 63 breaks .dev without SSL

### ISSUE THREAD

**Issue by subvertallchris** [puma/puma-dev#139]
I'm sure plenty of us read about this already, but in case you're a little late to the party...

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

Should/can puma-dev be changed to default to something like `.localhost` since `.dev` is essentially dead?

Fixing this for me as was easy as killing `puma-dev` in Activity Monitor, then...

```
puma-dev -install -d localhost
```

Just like the instructions demonstrate using `pdev`.

**Comment by JustinAiken** [comment]
Is there any workaround to make Chrome just work?  I've been using `.dev` for many years, don't want to switch everything to `localhost` or `test` just because of Googles whims..

**Comment by subvertallchris** [comment]
Doesn’t seem to be. Check out the link in my comment, it explains why.

**Comment by nyjt** [comment]
I've just started using Firefox Developer Edition because of this issue.

**Comment by nacengineer** [comment]
@nyjt which works right up until you realize how hooked on Google Developer Console. 😳

Hoping for a patch soon.

**Comment by jeromedalbert** [comment]
FYI pow switched from `.dev` to `.test`: https://github.com/basecamp/pow/pull/547.

**Comment by robertmiekwicz** [comment]
It looks like that .app domain is also affected. Redirecting me to https://

**Comment by richardonrails** [comment]
+1 for switching the default to `.test` like `pow` did.

**Comment by dwkns** [comment]
This happens in Safari 11.03 now too. So +1 for switching the default to `.test`

**Comment by JustinAiken** [comment]
But `.test` implies a test environment rather than a development environment..

**Comment by JustinAiken** [comment]
`.localdev` maybe?

**Comment by dwkns** [comment]
Much longer to type and could (in the future) be subject to the same problem as `.dev` where as `.test` wouldn't. 

Also others (such as [Pow](https://github.com/basecamp/pow) and [Invoker](https://github.com/code-mancers/invoker)) have already settled on `.test` so it's becoming a sudo-standard.

**Comment by subvertallchris** [comment]
This could easily be bikeshedded into oblivion. If `.test` is becoming the de facto standard, that seems like a good way to go in the interest of getting a new safe, usable default into the world.

**Comment by PostCucumber** [comment]
I'm getting the same issue with Firefox Developer addition after the update today.

**Comment by coorasse** [comment]
Would also be interesting to know how we will setup a OAuth2 redirect to a `.test` domain...
`.localhost` doesn't work either. `.dev`, of course, works since is a valid domain.
<img width="585" alt="screen shot 2018-02-19 at 19 25 32" src="https://user-images.githubusercontent.com/1319150/36392297-cbab797e-15aa-11e8-9bb8-f7d65a237f9a.png">

**Comment by nonrational** [comment]
FWIW @coorasse we ended up using a `company.io` domain and tricking pumadev into resolving them with some symlink magic.
A bit of a hack, but seems to be stable.

```
$ sudo puma-dev -d test:localhost:company.io -setup;
$ puma-dev -d test:localhost:company.io -install;

$ ls -l ~/.puma-dev
lrwxr-xr-x  1 nonrational  staff  37 Feb 10 14:29 app2@ -> ~/src/company/app2
lrwxr-xr-x  1 nonrational  staff  37 Feb 10 14:29 app2.company@ -> ~/src/company/app2
lrwxr-xr-x  1 nonrational  staff  34 Feb 10 14:29 app3@ -> ~/src/company/app3
lrwxr-xr-x  1 nonrational  staff  34 Feb 10 14:29 app3.company@ -> ~/src/company/app3
lrwxr-xr-x  1 nonrational  staff  36 Feb 10 14:29 app1@ -> ~/src/company/app1
lrwxr-xr-x  1 nonrational  staff  36 Feb 10 14:29 app1.company@ -> ~/src/company/app1

$ curl -I http://app1.company.io
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Company-Version: development
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: e567646b-39d7-4672-89d0-8f7999d151b3
X-Runtime: 0.250762
X-Xss-Protection: 1; mode=block
Date: Mon, 19 Feb 2018 18:36:03 GMT
```

**Comment by tmaier** [comment]
I would like to suggest to switch from `.dev` to `.localhost` to be in-line with other solutions in this space (e.g. hotel)

**Comment by tadman** [comment]
The good thing about `.d` is it is highly unlikely to be issued by ICANN, so it should be safe.

**Comment by seewhy17** [comment]
the .test TLD does not work for me when I have an active internet connection

**Comment by evanphx** [comment]
Sorry for the long delay, v0.12 is out now and switches the default domain to .test.
