### ISSUE TITLE
Middleman compatibility

### ISSUE THREAD

**Issue by alekseyg** [puma/puma-dev#142]
I don't know why, but about a third of my Middleman websites don't work on puma-dev. Middleman is a static site generator, but while running its server, it works a bit more like Rails or Sinatra, and in fact utilizes pieces of Rails and Padrino. The sites work on vanilla puma and Pow, but I can't figure out what makes them break randomly on puma-dev. I just get the "unexpected exit" error and the output of `curl -H "Host: puma-dev" localhost/events` isn't helpful either. Here is an example with one of my apps:
```
{"time":"2017-12-16 15:32:13.125577 -0800 PST m=+42809.995137069","event":"app_lookup","path":"/Users/aleksey/.puma-dev/appname"}
{"time":"2017-12-16 15:32:13.128969 -0800 PST m=+42809.998529844","event":"booting_app","app":"appname","socket":"/Users/aleksey/.puma-dev/appname/tmp/puma-dev-9690.sock"}
{"time":"2017-12-16 15:32:13.129107 -0800 PST m=+42809.998667129","event":"waiting_on_app","app":"appname"}
{"time":"2017-12-16 15:32:16.747621 -0800 PST m=+42813.617179785","event":"killing_app","app":"appname","pid":79466,"reason":"stdout/stderr closed"}
{"time":"2017-12-16 15:32:16.749464 -0800 PST m=+42813.619023283","event":"shutdown","app":"appname"}
{"time":"2017-12-16 15:32:16.749504 -0800 PST m=+42813.619062631","event":"lookup_error","error":"unexpected exit"}
{"time":"2017-12-16 15:32:16.749536 -0800 PST m=+42813.619094765","event":"dying_on_start","app":"appname"}
```
I tried matching the gem versions exactly with another app and taking it apart piece by piece, but that did work. I tried complex apps and simple ones. The ones that work, just work, and the ones that don't, simply don't. I'm not sure where to even start debugging; that's what is most frustrating. The log files for the apps also contain no errors, as though they started up correctly, except they simply don't have entries where a resource is actually served, since the resources weren't served.

**Comment by dikaio** [comment]
Receiving the same errors here. Did you find a fix @alekseyg?

**Comment by alekseyg** [comment]
@dikaio Unfortunately, no

**Comment by dikaio** [comment]
Hey @alekseyg I think your error is coming from your config.ru setup. Here's an example here:

```ruby
# frozen_string_literal: true

module Rack
  class TryStatic
    def initialize(app, options)
      @app = app
      @try = ['', *options.delete(:try)]
      @static = ::Rack::Static.new(lambda { [404, {}, []] }, options)
    end

    def call(env)
      orig_path = env['PATH_INFO']
      found = nil

      @try.each do |path|
        resp = @static.call(env.merge!({'PATH_INFO' => orig_path + path}))
        break if 404 != resp[0] && found = resp
      end

      found or @app.call(env.merge!('PATH_INFO' => orig_path))
    end
  end
end

use Rack::Deflater
use Rack::TryStatic,
  root: 'build',
  urls: %w(/),
  try: %w(.html index.html /index.html),
  cache_control: 'public, max-age=2592000'

# Run your own Rack app here or use this one to serve 404 messages:
run lambda { |env|
  not_found_page = File.expand_path('../build/404.html', __FILE__)
  content = File.exist?(not_found_page) ? File.read(not_found_page) : '404 - page not found'
  return [404, { 'Content-Type'  => 'text/html'}, [content]]
}
```

The problem with this setup is that while it does get puma-dev going with access on 80 and 443 it doesn't livereload work being done being that we have everything being served from the `build` folder. I'm configuring the external pipeline now to have gulp/browsersync watch file changes and see if that works out. I'll post here if it does.

**Comment by glennfu** [comment]
I'm having what I believe is a related issue. I've written a custom middleman service which involves me passing a custom Host header that differs from the actual site domain. This breaks puma-dev, but pow handles it correctly. With pow, the correct app gets the request, but sees the url as defined by the Host header. With puma-dev, I get "unknown app" as the response.

Using this command: `curl -H 'Host: www.custom-domain.com' -H 'Accept: */*' -H 'Accept-Language: en-us' --data-binary "" --compressed 'http://myapp.test/get_data'` I expect the site symlinked to `myapp` to get the request, but it doesn't.

**Comment by nonrational** [comment]
@glennfu puma-dev uses the `Host` header to look up which app to serve. Overriding it like `-H 'Host: www.custom-domain.com'` won't work.

Not sure how many use cases require custom `Host`s, but would consider a feature request if the case is laid out. 

Given the original topic has been stale since 2018, closing.

**Comment by glennfu** [comment]
When I’m testing apps with Charles, I sometimes do a remote rewrite to a rails app used for debugging/inspecting. When I want to use this (I did just last week) I have to uninstall puma-dev and reinstall pow. With puma-dev, it just doesn’t work.

**Comment by nonrational** [comment]
@glennfu fair enough! please open a new issue to track your feature request and we can figure out if it can make it into the 0.14 release.
