### ISSUE TITLE
App logs location

### ISSUE THREAD

**Issue by tylercoville** [puma/puma-dev#151]
Where should we expect the app logs to be? I have gotten it running in OSX using `puma-dev -setup` and `puma-dev -install` but my `{APP_BASE}/log/development.log` aren't populating properly. If I start the server using puma through `rails s` it starts and logs as expected.

**Comment by MindRave** [comment]
I would like to know this as well, if anyone has any info on the subject.

**Comment by evanphx** [comment]
Right now they get written to the stdout of puma-dev itself. I realize that's now ideal, might be good to write them into the log dir if it's there.

**Comment by evanphx** [comment]
I forgot to mention that if you installed puma-dev to run automatically, that file is `~/Library/Logs/puma-dev.log`

**Comment by jonathansimmons** [comment]
Sorry to be a nucanse but the application logs don't seem to be located here. the last entry is 

`! App 'app-name' booted`

I'm clearly navigating my app and making changes though. Am I missing something?

**Comment by JoHens** [comment]
same here, requests don't seem to get logged.

**Comment by JeremyEllingham** [comment]
It appears that there are two separate logs going on, one for puma-dev and one with console outputs.

@JoHens  @jonathansimmons might help to check in both.  If there's no explanation of this split by the repo owner I might submit a PR adding it to the Readme.

```bash
# Puma dev logs
$ curl -H "Host: puma-dev" localhost/events
# Tail the server logs 
$ tail -f ~/Library/Logs/puma-dev.log
```
