### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by annaswims** [puma/puma-dev#152]
When I did `brew install puma/puma/puma-dev`
I saw: 
````
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/puma/homebrew-puma/puma-dev.rb:30:in `caveats'
Please report this to the puma/puma tap!
````

**Comment by wjp2013** [comment]
me too.

* macOS 10.13.3
* Homebrew 1.5.2
* Homebrew/homebrew-core (git revision a6921; last commit 2018-02-01)

**Comment by nonrational** [comment]
This is a duplicate of https://github.com/puma/homebrew-puma/issues/5

**Comment by evanphx** [comment]
Fixed by the homebrew patch.
