### ISSUE TITLE
Application not detected and not booted

### ISSUE THREAD

**Issue by pothibo** [puma/puma-dev#156]
It seems like my application is not detected by puma-dev. I believe I followed the instruction but puma-dev completely ignores my application.

Here's the logs:
```
* Directory for apps: /Users/pothibo/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: inherited from launchd
* HTTPS Server port: inherited from launchd
! Puma dev listening on http and https
```

Then nothing. I did add my project path to `/Users/pothibo/.puma-dev` too, is there any way I can have more information about it?

I'm reading through the source code right now to try to find what might cause the issue but so far, not much. Sorry for the vague issue, I know these sucks but I ran out of idea

**Comment by mcrampon** [comment]
@pothibo I have the exact same problem and haven't been able to figure out what's going on. Have you found a solution to this?

**Comment by rubydog** [comment]
@pothibo did you find the solution? I am having the same issue.
