### ISSUE TITLE
Possible to use puma-dev with multiple domains?

### ISSUE THREAD

**Issue by gee-forr** [puma/puma-dev#157]
Hi there,

I was wondering if it's possible to use multiple domains with puma-dev... We like using a `.<client-name>` domain for our clients, but sometimes we need to use a valid domain when working with OAuth2 providers like google. In that case, we use `.pizza` as it's a real TLD, but not something we're likely to use in our day-to-day lives.

We find ourselves having to reconfigure puma-dev between projects, and it's a little tedious. I've tried variations of this command, and none work as expected.

```
puma-dev -install -d pizza,client
puma-dev -install -d pizza -d client
puma-dev -install -d pizza client
```

Also - thank you so much for puma-dev, it's been invaluable.

**Comment by kennethkalmer** [comment]
@gee-forr it seems from the code that you could separate multiple domains with colons (`:`). I haven't tried yet, just thought I'd pass this on

**Comment by gee-forr** [comment]
@kennethkalmer - that works perfectly. Thanks man :) 

I've issued PR #158 to update the readme.

I owe you a beer or something next time I bump into you.
