### ISSUE TITLE
Issue running puma-dev in Docker container

### ISSUE THREAD

**Issue by robbymarston** [puma/puma-dev#163]
Under "Install on Linux" in the README, it reads:

_Puma-dev supports linux but requires additional installation to make all the features work._

Curious, what do you mean by "additional installation?" I'm trying to run it in a Docker container and I keep getting this error: `standard_init_linux.go:190: exec user process caused "exec format error"` The error is typically associated with mismatching architectures; however, both the container and puma-dev are AMD64. The command it's trying to execute on that line is `puma-dev -install -d test`. Has anyone else experienced this?

Regarding the container, I'm using the official Ruby image which has the following setup:

**Kernal**
`Linux 969a18a21b75 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux`

**Distribution**
```
Distributor ID:    Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:    9.4
Codename:    stretch
```

**Comment by barrywoolgar** [comment]
Did you close this issue because you figured out what the problem was? It might help someone else in future if you could summarise the solution here before you forget it :)

**Comment by gkatsanos** [comment]
Exact same question, same issue. @robbymarston any idea?
