### ISSUE TITLE
SSL not working anymore

### ISSUE THREAD

**Issue by resistorsoftware** [puma/puma-dev#165]
Just fired up a Ruby 2.5.1 Rails 5.2 App and puma-dev, set for a custom port, seems to be having trouble. The specific message is:

SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

In my browser, Chrome 67, https://myapp.test works fine. No issues. But an oAuth callback to https://myapp.test/auth/callback generates this error. Any idea what might be the problem?

**Comment by resistorsoftware** [comment]
The Puma Dev CA certificate was no longer being found. I had to manually reset the openSSL cert chain to include this by exporting the CA file from OSX keychain as a PEM, then re-init the openSSL chain, and boom... certificates were found again. 

So how does this happen, that the CA file for Puma Dev gets lost in the shuffle?

**Comment by pusewicz** [comment]
@resistorsoftware Care to provide the steps for that?

**Comment by resistorsoftware** [comment]
I quit using puma-dev some time ago as it was no longer useful to me. Sorry.

**Comment by mattscilipoti** [comment]
@resistorsoftware What are you using instead?

**Comment by resistorsoftware** [comment]
I came back to puma-dev with a new pattern of use. Still, one has to approve the certificate in the keychain.
