### ISSUE TITLE
Can you publish a new release?

### ISSUE THREAD

**Issue by rmacklin** [puma/puma-dev#166]
@evanphx would you be able to publish a new release of `puma-dev`? There have been a lot of great additions since the last release (`0.11`): https://github.com/puma/puma-dev/compare/0.11...d4c06730d310c95255df9200bbaf9e640615ea99, and I would love if my coworkers could get those improvements just from the simple `brew install` command.

**Comment by rmacklin** [comment]
In particular, after suggesting my coworkers switch from pow to puma-dev, I found that several of them had mistakenly followed `master`'s README which [says]:(https://github.com/puma/puma-dev/tree/d4c06730d310c95255df9200bbaf9e640615ea99#install-on-macos)

> Run `puma-dev -install` to configure puma-dev to run in the background on ports 80 and 443 with the domain `.test.`

and:

> Default domain is `.test`. Previously it was `.dev`, but it is owned by Google and since Dec 2017 **HSTS only** with real websites hosted there.

However, the latest release does not include the change that switches the default to `.test`, so my coworkers were confused when this wasn't working. Of course, they can manually specify `puma-dev -install -d test`, but it'd be awesome if a new release was published so they could just follow the README as-is.

**Comment by evanphx** [comment]
Sorry for the long delay, v0.12 is out now with that change.

**Comment by rmacklin** [comment]
Thank you @evanphx!
