### ISSUE TITLE
puma-dev -install throws a launchd error

### ISSUE THREAD

**Issue by BJClark** [puma/puma-dev#17]
I installed puma-dev via homebrew on 10.11.6. Running the commands it outputs, when I run `puma-dev -install` I get the follow:

`7/29/16 12:02:54.766 PM com.apple.xpc.launchd[1]: (io.puma.dev[3529]) Service could not initialize: 15G31: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
7/29/16 12:02:54.766 PM com.apple.xpc.launchd[1]: (io.puma.dev) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
`

This repeats every 10 seconds until I uninstall.

**Comment by evanphx** [comment]
Can you gist the contents of "~/Library/Logs/puma-dev.log"?

**Comment by BJClark** [comment]
I re-did the install instructions and now I'm getting #12. I'll close this and go with that one.
