### ISSUE TITLE
SSL Error with self-signed certificate in dev when using Chrome 70

### ISSUE THREAD

**Issue by eric-norcross** [puma/puma-dev#182]
I'm using:

- `ruby 2.5.3`
- `rails 5.1.6`
- `puma 3.12.0`
- `macOS 10.14.1`
- `Chrome Version 70.0.3538.77 (Official Build) (64-bit)`
- I've created a self-signed certificate following the Heroku instructions [here](https://devcenter.heroku.com/articles/ssl-certificate-self)
- I have the following in my `hosts` file:

```
    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost
    127.0.0.1 localhost.ssl
```

- Added the self-signed certificate to my `system` keychain and always trusted it
- In my `puma` config file, i'm starting puma with: `ssl_bind '127.0.0.1', '8080', { key: 'localhost_ssl/server.key', cert: 'localhost_ssl/server.crt', verify_mode: 'none' }`

When attempting to connect on Chrome 70, Chrome shows the following error 
<img width="685" alt="screen shot 2018-11-01 at 9 14 21 am" src="https://user-images.githubusercontent.com/1047774/47864405-be391b00-ddb6-11e8-81d1-cf9baba31beb.png">

When accessing `https://localhost:8080` on `FireFox 63.0 (64-bit)` I'm prompted to add a one-time security exception in order connect. `Safari Version 12.0.1` has no issue connecting. 

And `puma` logs the following: `SSL error, peer: 127.0.0.1, peer cert: , #<Puma::MiniSSL::SSLError: OpenSSL error: error:141F7065:SSL routines:final_key_share:no suitable key share - 337604709>`

Any advice would be appreciated.

**Comment by dachinat** [comment]
So, is there a solution?

**Comment by martingalovic** [comment]
+1

**Comment by nonrational** [comment]
Closing as this appears to be related to puma, not puma-dev.
