### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by sj26** [puma/puma-dev#184]
Is puma-dev being maintained? Would you like help?

**Comment by exactchange** [comment]
I think it's safe to say they need help – _a lot_.

**Comment by hopewise** [comment]
It seems its not maintained any more? what's the alternative?

**Comment by h0jeZvgoxFepBQ2C** [comment]
@brixen @evanphx @jordanisip @nateberkopec any thoughts about if this gem is still maintained? Would you accept new maintainers to help out?

**Comment by nateberkopec** [comment]
Yes, I am PR/issue gardening here now.
