### ISSUE TITLE
App is immediately dying using Rbenv 1.9.3

### ISSUE THREAD

**Issue by jgervin** [puma/puma-dev#186]
I am having the same issue but using Rbenv. I have set Rbenv to local 1.9.3 but the app immediatley crashes and the browser says from /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `

'
Not sure why it is using ruby 2.3.1 as rbenv versions says project directory is set to 1.9.3

statrubytwotwo jn$ curl -H "Host: puma-dev" localhost/events
{"time":"2018-11-28 16:48:36.558649141 -0600 CST m=+1.842019417","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.56016005 -0600 CST m=+1.843530082","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.56042688 -0600 CST m=+1.843796869","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 16:48:36.560697991 -0600 CST m=+1.844067936","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.563621524 -0600 CST m=+1.846990997","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.566312331 -0600 CST m=+1.849681369","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.566653184 -0600 CST m=+1.850022167","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 16:48:36.566922009 -0600 CST m=+1.850290948","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.567388078 -0600 CST m=+1.850756942","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 17:11:33.714593989 -0600 CST m=+1378.966720495","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:11:33.745253605 -0600 CST m=+1378.997380581","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:11:33.755257474 -0600 CST m=+1379.007384603","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:35.905097341 -0600 CST m=+1381.157257426","event":"killing_app","app":"statrubytwotwo","pid":15392,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:11:35.910976285 -0600 CST m=+1381.163136460","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:35.911053843 -0600 CST m=+1381.163214019","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in <main>'\n"} {"time":"2018-11-28 17:11:35.911306417 -0600 CST m=+1381.163466597","event":"dying_on_start","app":"statrubytwotwo"} {"time":"2018-11-28 17:11:37.779555541 -0600 CST m=+1383.031744360","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"} {"time":"2018-11-28 17:11:37.798043921 -0600 CST m=+1383.050233024","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"} {"time":"2018-11-28 17:11:37.798263999 -0600 CST m=+1383.050453105","event":"waiting_on_app","app":"statrubytwotwo"} {"time":"2018-11-28 17:11:39.681402782 -0600 CST m=+1384.933620755","event":"killing_app","app":"statrubytwotwo","pid":15526,"reason":"stdout/stderr closed"} {"time":"2018-11-28 17:11:39.681754835 -0600 CST m=+1384.933972813","event":"shutdown","app":"statrubytwotwo"} {"time":"2018-11-28 17:11:39.681893219 -0600 CST m=+1384.934111200","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in

'\n"}
{"time":"2018-11-28 17:11:39.682519064 -0600 CST m=+1384.934737054","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:22.45541228 -0600 CST m=+1427.708285948","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:22.490191345 -0600 CST m=+1427.743065546","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:22.493597677 -0600 CST m=+1427.746471931","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:24.313665766 -0600 CST m=+1429.566567921","event":"killing_app","app":"statrubytwotwo","pid":15741,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:24.313836024 -0600 CST m=+1429.566738182","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:24.313890622 -0600 CST m=+1429.566792780","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in <main>'\n"} {"time":"2018-11-28 17:12:24.314462757 -0600 CST m=+1429.567364924","event":"dying_on_start","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:26.426601154 -0600 CST m=+1431.679535698","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"} {"time":"2018-11-28 17:12:26.436611439 -0600 CST m=+1431.689546136","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"} {"time":"2018-11-28 17:12:26.436792476 -0600 CST m=+1431.689727176","event":"waiting_on_app","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:27.675985747 -0600 CST m=+1432.928939444","event":"killing_app","app":"statrubytwotwo","pid":15875,"reason":"stdout/stderr closed"} {"time":"2018-11-28 17:12:27.676132059 -0600 CST m=+1432.929085758","event":"shutdown","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:27.676165648 -0600 CST m=+1432.929119347","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in '\n"}
{"time":"2018-11-28 17:12:27.67682828 -0600 CST m=+1432.929781990","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:50.880388784 -0600 CST m=+1456.133698190","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:50.909920214 -0600 CST m=+1456.163230073","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:50.917031594 -0600 CST m=+1456.170341562","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:52.065640798 -0600 CST m=+1457.318968373","event":"killing_app","app":"statrubytwotwo","pid":16053,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:52.065771399 -0600 CST m=+1457.319098976","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:52.065805476 -0600 CST m=+1457.319133053","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in <main>'\n"} {"time":"2018-11-28 17:12:52.065980271 -0600 CST m=+1457.319307851","event":"dying_on_start","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:52.568960015 -0600 CST m=+1457.822295305","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"} {"time":"2018-11-28 17:12:52.575589621 -0600 CST m=+1457.828925013","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"} {"time":"2018-11-28 17:12:52.575733689 -0600 CST m=+1457.829069083","event":"waiting_on_app","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:53.657831663 -0600 CST m=+1458.911183645","event":"killing_app","app":"statrubytwotwo","pid":16181,"reason":"stdout/stderr closed"} {"time":"2018-11-28 17:12:53.658017688 -0600 CST m=+1458.911369673","event":"shutdown","app":"statrubytwotwo"} {"time":"2018-11-28 17:12:53.658151214 -0600 CST m=+1458.911503201","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in '\n"}
{"time":"2018-11-28 17:12:53.661413974 -0600 CST m=+1458.914766011","event":"dying_on_start","app":"statrubytwotwo"}

**Comment by jgervin** [comment]
Update GemFile, local and global rbenv to 2.3.1 

Same issue.

**Comment by nonrational** [comment]
Closing as stale. Please provide an update if you're still experiencing this issue on v0.13.
