### ISSUE TITLE
Opens port 80 but puma-dev not running

### ISSUE THREAD

**Issue by ssk** [puma/puma-dev#189]
I have several Macs and some of them works with puma-dev well and others not.

After "puma-dev -install", I can telnet to port 80 and lsof shows launchd with HTTP which I guess puma-dev created.
But puma-dev itself is not loaded. 
I guess there's some error while it's loading.

`ssk@ssk-mac-mini:~$ puma-dev -uninstall
* Removed puma-dev from automatically running
* Removed domain 'test'
ssk@ssk-mac-mini:~$ sudo lsof -i:80
Password:
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ssk@ssk-mac-mini:~$ puma-dev -install
* Use '/usr/local/Cellar/puma-dev/0.12/bin/puma-dev' as the location of puma-dev
* Installed puma-dev on ports: http 80, https 443
ssk@ssk-mac-mini:~$ sudo lsof -i:80
COMMAND PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
launchd   1 root    9u  IPv4 0x5d9e14e84cdd38d1      0t0  TCP *:http (LISTEN)
ssk@ssk-mac-mini:~$ ps aux | grep puma
ssk               9956   0.0  0.0  4268020    780 s002  S+    7:46AM   0:00.00 grep puma
ssk@ssk-mac-mini:~$ telnet 127.0.0.1 80
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
`

**Comment by ivellios** [comment]
To me it looks like `-uninstall` option not working at all. Puma was still working as a self-restarting daemon and killing it doesn't help. I cannot uninstall it, though what I did was to change the `/usr/local/Cellar/puma-dev/0.12/bin/puma-dev` filename to `/usr/local/Cellar/puma-dev/0.12/bin/puma-dev.bak`

Then kill the process and it didn't come back. Port 80 is now free.

**Comment by nonrational** [comment]
Please follow the [macOS setup instructions](https://github.com/puma/puma-dev/blob/master/README.md#install--setup) for the latest version (v0.13) and report back if you're still having issues.
