### ISSUE TITLE
Is the self signed root CA a potential security hole

### ISSUE THREAD

**Issue by brendon** [puma/puma-dev#192]
Sorry, I accidentally submitted the issue before I could write a description :)

Please refer here: https://github.com/vuejs/vue-devtools/pull/895#issuecomment-475369694

Given the root CA is a part of the default installation procedure (from memory?) should there be some documentation or a warning in the installer regarding the risks associated with this as raised by @felixbuenemann?

Keen to hear your thoughts :)

**Comment by bf4** [comment]
if you give the internet access to your development machine, that's not really the fault of puma-dev

in any case, ssl is ssl

**Comment by nonrational** [comment]
Closing as duplicate of #215
