### ISSUE TITLE
Puma-dev blocking access to production level .dev domains 

### ISSUE THREAD

**Issue by leesheppard** [puma/puma-dev#194]
Now that Google has released the `.dev` domain it seems that previously used puma-dev settings now prevent the loading of websites with the TLD extension. Flutter for example will not load if you have puma-dev installed with the `.dev` setting: https://flutter.dev/

I removed `etc/resolver/dev` and the page loads. But using the `.test` option with puma-dev does not appear to work locally. It is installed in that directory though.

**Comment by leesheppard** [comment]
Just found the article about binding to a new domain. 

https://www.dunkman.me/blog/2017/replacing-pow-with-puma-dev.html

In short, you can run `$ puma-dev -install -d test` where test is the extension name you want to use to load local env tests. Then running `$ puma-dev link` in each app directory to link to the new name.

**Comment by idyll** [comment]
Don't use `.test` if you have apps with subdomains. Something bad happens to the cookies needed for authentication.

**Comment by a17levine** [comment]
To work around it, I've been doing on OSX.

Seems to be undone on restart fyi

```bash
# commenting out the contents of this file
sudo nano /etc/resolver/dev
# restarting the mac osx dns service (I think)
sudo killall -HUP mDNSResponder
```

**Comment by nonrational** [comment]
`puma-dev` has moved to a default TLD of `.test` for the time being, but that can be overridden with the `-d` flag. Now that `.dev` is an official TLD, `puma-dev` doesn't want to be in the business of owning it.
