### ISSUE TITLE
Documentation should mention puma dependency

### ISSUE THREAD

**Issue by jamesgecko** [puma/puma-dev#198]
The setup instructions should probably mention running the `gem install puma` command, if the user doesn't already have it installed.

As someone unfamiliar with the distinction between `puma` and `puma-dev`, it took me a few hours to figure out that the error `bash: line 23: exec: puma: not found` was not because of a configuration error, but because puma-dev does not include puma. I initially assumed that puma-dev was mutually exclusive with puma because they were both described as servers! 😆

**Comment by nonrational** [comment]
https://github.com/puma/puma-dev/pull/195 (merged) resolves this.
