### ISSUE TITLE
Ubuntu 18.04.1 : `ping` and `curl` works but not browsers

### ISSUE THREAD

**Issue by gabriel-cardoso** [puma/puma-dev#205]
I'm trying to run my app with puma-dev on my new Linux Mint Tessa (Ubuntu 18.04.1) machine. 

I have all installed and set up, [`dev-tld-resolver`](https://github.com/puma/dev-tld-resolver) set up and `puma-dev` running correctly. 

`ping my-app.test` works

even `curl http://my-app.test` works !!

But when visiting http://my-app.test on 

- Google Chrome, I get an `ERR_NAME_NOT_RESOLVED`
- Google Chrome private mode, I get `DNS_PROBE_FINISHED_NXDOMAIN`
- Firefox, "Hmm. We’re having trouble finding that site. We can’t connect to the server at my-app.test"

But wait... it works well in both browsers when launching

`google-chrome http://my-app.test` 
`firefox http://my-app.test` 

from the terminal after killing every `pid`'s !

Really stuck here... Any clue ?

**Comment by nateberkopec** [comment]
Does this happen for TLDs that aren't "test"? [Test is a weird TLD](https://en.wikipedia.org/wiki/.test)

In any case, sounds like browser behavior and not puma-devs fault, so I'll close.

**Comment by gabriel-cardoso** [comment]
It indeed works with `.localhost` extension. I had no issues on Ubuntu 16.04 so far. I'll dig and see if I can understand what's the issue.

Thanks a lot @nateberkopec

**Comment by minimul** [comment]
I'm on 22.04 and the same issue occurred. Curl and w3m worked fine using `.test` to my puma-dev'd apps but not Chromium not Firefox. FWIW 20.04 didn't have this issue.

The `.localhost` domain did work fine.

I tried many things from different sources and nothing worked. I just then hardcoded my `*.test` domains into the localhost entry for `/etc/hosts` and now I can use the `.test` domains with puma-dev.

**Comment by Hiren-Cialfo** [comment]
@minimul 
I've tried `.localhost` and it worked but I have to add port as well.
like `something.localhost:3000` etc.
and same works without subdomain `something`. 

Did I misunderstood something?

**Comment by minimul** [comment]
@Hiren-Cialfo I'd say that's a different problem then this issue. I'd say puma-dev is not binding to 80/433 but I see in your screenshot from the other issue that it is. But I also see that you are trying to use `.dev`. Did you run through the puma-dev DNS configuration instructions setting up `.dev` for resolution?

**Comment by Hiren-Cialfo** [comment]
Yes, I've tried.
