### ISSUE TITLE
Any plans for Linux support?

### ISSUE THREAD

**Issue by mamantoha** [puma/puma-dev#21]
The question probably for the devs.
Are there plans for Linux support? And if an answer is `yes` do you know how soon we will see this?

**Comment by evanphx** [comment]
There ya go! I'll release that on Monday but you're free to build and try it out. There are special install steps in the README to make `.dev` domains and ports 80/443 work.

**Comment by mamantoha** [comment]
That was fast. Thank you!

I've try to build it and get this error:

```
$ git clone git@github.com:puma/puma-dev.git

$ cd puma-dev

$ make
gb build cmd/puma-dev
make: gb: Command not found
make: *** [Makefile:2: all] Error 127

$ gb build cmd/puma-dev
fatal: Not a valid object name: 'cmd/puma-dev'.
```
