### ISSUE TITLE
How do you stop, start, restart on OS X? #111

### ISSUE THREAD

**Issue by chrishough** [puma/puma-dev#212]
This issue https://github.com/puma/puma-dev/issues/111 has not been fixed.

**Comment by nateberkopec** [comment]
What hasn't been fixed?

To restart Puma: $ pkill -USR1 puma-dev
To stop: $ puma-dev -stop

**Comment by chrishough** [comment]
As mentioned in the other posts those commands are not working. It starts right back up. I had to uninstall it forcefully.  One item to note, is it was installed via homebrew.

**Comment by nateberkopec** [comment]
Maybe something is making a request to port 80 in the background. That would cause the app to start back up again.

Just to confirm, `pkill` does exist on your system, right?

**Comment by nateberkopec** [comment]
Also if you could post your logs that would help. https://github.com/puma/puma-dev#logging

**Comment by chrishough** [comment]
I am wondering if it is installed via Homebrew has something to do with this, I will have to test this later and let you know.

**Comment by nonrational** [comment]
@chrishough Are you referring to the parent `puma-dev` process "start[ing] right back up"? Is your expectation that `kill`ing puma-dev should stop it from appearing in the process list? That's how I'm interpreting your comment.

`puma-dev -install` registers puma-dev as a system service with launchd, so `killall puma-dev` will cause launchd to automatically start a new process. If you want to stop the parent `puma-dev` from running in the background, you'll need to avoid installing it as a service. i.e. Don't run `puma-dev -install`.

**Comment by chrishough** [comment]
Yes, that is the case.  I fear that is home homebrew installs it.  I will have to confirm that.

**Comment by chrishough** [comment]
How I fixed this, was used homebrew to install it like the docs stated, then I ran `puma-dev -stop`  followed up by `puma-dev -uninstall`. This appears to have killed the service. Now I can run `puma-dev` without the daemon.

**Comment by fguillen** [comment]
> This appears to have killed the service. Now I can run `puma-dev` without the daemon.

The long command is this:

    sudo puma-dev -d pizza -http-port 80 -https-port 443
