### ISSUE TITLE
Avoid running as a daemon and install with test

### ISSUE THREAD

**Issue by chrishough** [puma/puma-dev#213]
I am trying to tinker with running puma-dev as follows...

```
brew install puma/puma/puma-dev
sudo puma-dev -setup -d test
puma-dev -install -d test
```

However, I need to avoid puma dev from both running as a deamon and taking control of the local port forwarding when it is not running.  I literally have to uninstall it to avoid it from conflicting with my docker nginx proxy setup.  

Thoughts?

**Comment by nonrational** [comment]
I'm not sure what you're trying to accomplish. Can you provide more context? 

The behavior you're describing is intended. `puma-dev` wants to own the default http/s ports. If you want to run docker+nginx on port 80, you can't run puma-dev on the same ports. You're welcome to set a non-default port via flags, (e.g. `puma-dev -http-port 8080`)

https://github.com/puma/puma-dev/blob/4f7cdd26ac09ce79108bc2bda15bed017edcd074/cmd/puma-dev/main_darwin.go#L20-L22
