### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by melvinotieno** [puma/puma-dev#258]
I am using a linux OS specifically Fedora 32 and I do not know where to get started. In the docs it says i should first start puma-dev, how do i ago about that? Is there something i should first do and how do i do it?

**Comment by nonrational** [comment]
https://github.com/puma/puma-dev#pre-built-binaries

You'll need to download and "install" `puma-dev` via pre-built binaries (placed in a directory on your `$PATH`) or build directly from source (and place `$GOBIN_PATH` on your `$PATH`). Given the limited support for linux, we do not currently provide a packaged installer (e.g. `yum`, `apt`, etc.).

**Comment by melvinotieno** [comment]
> https://github.com/puma/puma-dev#pre-built-binaries
> 
> You'll need to download and "install" `puma-dev` via pre-built binaries (placed in a directory on your `$PATH`) or build directly from source (and place `$GOBIN_PATH` on your `$PATH`). Given the limited support for linux, we do not currently provide a packaged installer (e.g. `yum`, `apt`, etc.).

@nonrational So how exactly do i download and install the pre-built binaries assuming that i'm a noob

**Comment by nonrational** [comment]
> ... assuming that i'm a noob

FWIW I might advise sticking to `rails s` and `http://localhost:3000` for now. The linux experience isn't automagic and getting the value out of puma-dev on linux will take a good deal of effort on your part. 

That being said, if you're set on going down this path, https://github.com/puma/puma-dev/issues/155 will be helpful. Please read and follow-up on that thread if you have additional question. Below are instructions to manually install the puma-dev linux binary.

```bash
# download the archive containing the binary
wget https://github.com/puma/puma-dev/releases/download/v0.14/puma-dev-0.14-linux-amd64.tar.gz
# unpack the archive with tar
tar xvzf puma-dev-0.14-linux-amd64.tar.gz
# as root, move the unpacked binary into the "local" bin where non-default binaries commonly go
sudo mv puma-dev /usr/local/bin/
# run puma-dev and get the version
puma-dev -V
# clean up
rm puma-dev-0.14-linux-amd64.tar.gz
```

**Comment by melvinotieno** [comment]
Thank you for the reply

> FWIW I might advise sticking to `rails s` and `http://localhost:3000` for now. The linux experience isn't automagic and getting the value out of puma-dev on linux will take a good deal of effort on your part.
> 

Problem is i really want to test subdomains locally and this is the only solution that i can currently find as i do not want to edit the etc/host file

**Comment by nonrational** [comment]
If you just want DNS to test sub/domains, I'd suggest using `dnsmasq`. It likely does what you want and there are [plenty of blog posts](https://brunopaz.dev/blog/setup-a-local-dns-server-for-your-projects-on-linux-with-dnsmasq) about how to configure it.

**Comment by melvinotieno** [comment]
Thank you, does exactly what i wanted.

**Comment by memon** [comment]
With homebrew now available on linux, what would be required to create a puma-dev brew recipe?

**Comment by nonrational** [comment]
@memon done! https://github.com/puma/homebrew-puma/pull/12
