### ISSUE TITLE
Freshly built binary does not work

### ISSUE THREAD

**Issue by momolog** [puma/puma-dev#265]
I am trying to build and run a modified version of puma-dev from master.

I did a `make build` and got an executable `./puma-dev`.

No when I run it like `./puma-dev -dir /Users/aljoscha/.puma-dev -d test -timeout 15m0s` I get the following output:
```
2020/11/26 21:22:48 Existing valid puma-dev CA keypair found. Assuming previously trusted.
* Directory for apps: /Users/aljoscha/.puma-dev
* Domains: test
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev running...
```
which looks very promising. However a local app `example.test` is not served (`example.test` correctly resolves to 127.0.0.1).  

What am I missing?

--- 

### update

I get the same result when I follow the steps in https://github.com/puma/puma-dev#build-from-source

**Comment by nonrational** [comment]
It looks like you're running puma-dev in the foreground. Have you tried `http://example.test:9280` ?

If you [install & setup](https://github.com/puma/puma-dev#install--setup), you shouldn't need to run it in the foreground.
