### ISSUE TITLE
MacOS M1 Arm problem

### ISSUE THREAD

**Issue by resistorsoftware** [puma/puma-dev#279]
I installed via Homebrew in a terminal where I see the compilation was for Apple, so M1, not Rosetta. 

Puma-dev seems to work somewhat with dot test domain, but fails with grok tunnels. For example, if I call up ngrok.com and see my endpoints for my App fizzbuzz.ngrok.io,  that URL never works. Ngrok complains both the HTTP and HTTPS endpoints are not responding. So that is weird. 

If I just do my https://fizzbuzz.test in my browser, the App,  it works fine. 

What am I forgetting to do to get Puma Dev working on a new M1 machine? For some reason it is blocking ports or something? 

When I do start my App, I see puma-dev is working, but the logs show no entry such as this, from my working Intel machine. The M1 logs remain empty of these notes? My PORT is set to 3145 for the file fizzbuzz in the ~/.puma-dev directory.

* Generated proxy connection for 'fizzbuzz' to http://127.0.0.1:3145

So if this entry is missing, what is that telling me? 

End result, any access to the .test domains from my ngrok tunnel results in this? No ideas. My older Intel machine with Puma Dev does not suffer from this! 
<img width="671" alt="ngrok_io" src="https://user-images.githubusercontent.com/123307/119547106-aeadc300-bd62-11eb-9122-b72ea0793e94.png">

**Comment by nonrational** [comment]
> I installed via Homebrew in a terminal where I see the compilation was for Apple, so M1, not Rosetta.

FWIW the current homebrew formula doesn't install the M1 binary. That's still a [work in progress](https://github.com/puma/puma-dev/issues/273). You can download the M1 build manually, but it won't automatically install via brew (as of 2021-05-31).

I'm not very familiar with how ngrok works, but, from the error message, it looks like it's trying to do DNS lookup on :53. But, by default, `puma-dev` serves its DNS on :9253.

You can use `scutil --dns` to verify the DNS settings your machine is using, and check in `/etc/resolver/*` to see if `puma-dev`'s resolvers have been installed correctly. 

```
$ cat /etc/resolver/test
# Generated by puma-dev
nameserver 127.0.0.1
port 9253
```

**Comment by resistorsoftware** [comment]
Thanks for the tips. I wonder how the build proceeded from Homebrew, without incident, and shows up in Activity monitor as Apple and not Intel?

**Comment by nonrational** [comment]
Yeah, that's puzzling. You can use `file path/to/puma-dev` to inspect the binary's contents, and I expect it will return `Mach-O 64-bit executable x86_64`.

**Comment by resistorsoftware** [comment]
That is exactly the result!

**Comment by nonrational** [comment]
arm64 build is now available in Homebrew.
