### ISSUE TITLE
Actioncable /cable not found

### ISSUE THREAD

**Issue by navied** [puma/puma-dev#28]
I seem to be having some issues with getting actioncable working in-app, it resulting in 404 errors in the browser and these errors in the logs:

Started GET "/cable" for 127.0.0.1 at 2016-07-31 21:04:47 -0400
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: , HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 127.0.0.1 at 2016-07-31 21:04:41 -0400

**Comment by evanphx** [comment]
Does actioncable work when you just run the app normally via `puma`? I believe you might have to setup some additional routes?

**Comment by navied** [comment]
Yep it works when you run the app via rails s, the only difference I saw between the puma settings of both is that the min threads is 5 in rails s versus 0. I doubt that is why it is causing issues though. 



On Mon, Aug 1, 2016 at 1:47 PM -0400, "Evan Phoenix" <notifications@github.com> wrote:












Does actioncable work when you just run the app normally via puma? I believe you might have to setup some additional routes?

**Comment by kobaltz** [comment]
I've tested this out a bit and also experienced the same issue.

I even set the to `config.action_cable.allowed_request_origins` to `/(.*?)/` to allow from all domains.

**Comment by evanphx** [comment]
@navied Ok, but what about when you run it via `puma` rather than `rails s`?

**Comment by navied** [comment]
Running it through "bundle exec puma -C config/puma.rb" works as well, here are the contents of puma.rb:

```
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i
threads threads_count, threads_count

port        ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

plugin :tmp_restart
```

**Comment by evanphx** [comment]
That... odd. What about doing just `bundle exec puma`? puma-dev just passes things straight through so I'm not sure why it would cause issues like this...

**Comment by navied** [comment]
Doing a simple bundle exec puma works as well. It is an odd issue, could it be something to do with the tld?

**Comment by evanphx** [comment]
So basically puma-dev was mangling websocket requests entirely. 19be13b fixes that.

You also need to configure rails to allow websocket requests. The quickest way is to add `  config.action_cable.disable_request_forgery_protection = true` to `config/environments/development.rb`.

Or you can add do something like `config.action_cable.allowed_request_origins = /(\.dev$)|^localhost$/` to allow anything under `.dev` as well as `localhost`.

**Comment by navied** [comment]
Amazing, thanks a lot for the speedy fix 💯

**Comment by evanphx** [comment]
@navied No problem! I'll have a release with the fix out tonight or tomorrow.
