### ISSUE TITLE
does not listen to 443

### ISSUE THREAD

**Issue by hopewise** [puma/puma-dev#296]
When I try to load the website with https, and check logs, I see nothing in logs, also, in browser, I get 404
it works only at http, however, I have run this command:

```
puma-dev -install-https-port 443
```
Why there isn't any log when I use https? and how to issue a valid certificate that chrome would trust?

**Comment by nonrational** [comment]
Please see [Install & Setup](https://github.com/puma/puma-dev#install--setup), which will generate and trust certs and, by default, configure puma-dev to listed on 443.
