### ISSUE TITLE
Ruby debugger?

### ISSUE THREAD

**Issue by joelmoss** [puma/puma-dev#309]
It would be awesome of puma-dev worked with the Ruby [debug](https://github.com/ruby/debug) gem, but I've not been able to get it working.

Is this possible? Has anyone managed to integrate the two at all?

**Comment by joelmoss** [comment]
ok, so I was missing the `require 'debug/open_nonstop'`. Once I add that, I can attach with `rdbg -A`!

Sorry for wasting your time, and thx

**Comment by joelmoss** [comment]
One annoyance that I keep coming across when I start rdbg, is that is always pauses on puma/single.rb:61 on startup. I'm assuming this has something to do with the `rescue` being used there? Is there a way to ignore that?

**Comment by nonrational** [comment]
I think this may be a question better posted to [`puma/puma`](https://github.com/puma/puma) rather than puma-dev?
