### ISSUE TITLE
puma-dev not working in Ubuntu 22.04 with Rails 4

### ISSUE THREAD

**Issue by Hiren-Cialfo** [puma/puma-dev#312]
Ruby - 2.4.7
Rails - 4.2.1
puma-dev: Version: 0.18.2 (go1.17.6)

Here is the file in the .puma-dev directory

![Screenshot from 2022-06-18 23-17-40](https://user-images.githubusercontent.com/89768024/174450554-453b3cac-0e37-41de-87d4-794dc808b82e.png)

When I start the rails server and hit the url in browser it gives some error.

![Screenshot from 2022-06-18 23-12-26](https://user-images.githubusercontent.com/89768024/174450534-74ae09d8-1fe0-4f76-beb7-32af4e472c68.png)

puma-dev is up and running

![Screenshot from 2022-06-18 23-19-48](https://user-images.githubusercontent.com/89768024/174450618-1df1cc80-af4f-48d0-9e5e-fc753645760e.png)

Sometime I face `503 Service Temporarily Unavailable` error as well, when I add another file in the `.puma-dev` directory with different port.

Please help me.

**Comment by nonrational** [comment]
Have you tried accessing your app via HTTP instead of HTTPS? The error in your screenshot indicates that you haven't trusted your [Puma-dev CA](https://github.com/puma/puma-dev#puma-dev-root-ca).

**Comment by minimul** [comment]
@Hiren-Cialfo See here https://github.com/puma/puma-dev/issues/205#issuecomment-1225944812
