### ISSUE TITLE
"unexpected exit: 	No puma executable found for ruby system"

### ISSUE THREAD

**Issue by NV** [puma/puma-dev#313]
I'm trying to serve a static website on `blah.test`. Previously, I used Pow for that.

When I open `http://blah.test/` I see:
```
unexpected exit:
	No puma executable found for ruby system
```

Instead of ~/Code/blah/website/index.html.

```
~/.puma-dev/blah ⮀ls -l
total 0
lrwxr-xr-x  1 nv  staff  36 Jun 20 07:55 public@ -> /Users/nv/Code/blah/website
drwxr-xr-x  3 nv  staff  96 Jun 20 07:55 tmp/
```

**Comment by nonrational** [comment]
Any "app" managed by puma-dev will still try to boot puma. There's a workaround in #87.
