### ISSUE TITLE
[BUG] puma-dev does not compiles on Linux

### ISSUE THREAD

**Issue by hron84** [puma/puma-dev#32]
It seems like README was not updated with the latest requirements to build `puma-dev` successfully. 

The following error happens:

```
[hron@moonshine puma-dev (master)] $ go version
go version go1.6.3 linux/amd64
[hron@moonshine puma-dev (master)] $ make
gb build cmd/puma-dev
FATAL: command "build" failed: failed to resolve import path "cmd/puma-dev": import "flag": not found: stat /home/hron/build/puma-dev/src/flag: no such file or directory
make: *** [Makefile:2: all] Error 1
[hron@moonshine puma-dev (master)] $
```

Please:

 - Update README with correct requirements
 - And possibly provide Linux builds too.

**Comment by evanphx** [comment]
That's pretty weird. I'm not able to replicate the issue, is perhaps your go installation not installed to `/usr/local/go`? I believe it needs to be there so that the standard packages can be found.

**Comment by cmwall** [comment]
Having this same issue on Ubuntu 16.04.

```
➜  puma-dev-0.7 go version
go version go1.6.3 linux/amd64
➜  puma-dev-0.7 make
gb build cmd/puma-dev
FATAL: command "build" failed: failed to resolve import path "cmd/puma-dev": import "github.com/fsnotify/fsevents": not found: stat /home/cody/Desktop/puma-dev-0.7/src/github.com/fsnotify/fsevents: no such file or directory
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
➜  puma-dev-0.7 which go
/usr/local/go/bin/go
➜  puma-dev-0.7 
```

The fsevents package is apparently only for Mac and the `github.com/` directory is not available in the `src/` directory - it's in the `vendor/` directory. Not sure if that would cause any issues with package installation.

**Comment by evanphx** [comment]
That package shouldn't be compiled at all on linux, it's in a darwin specific file...

**Comment by evanphx** [comment]
@cmwall I was unable to replicate the issue on 14.04 (I'm on a slow internet connection and can't download 16.04 right now). I installed go, installed gb, and make worked fine. Can you try deleting the pkg/ and vendor/pkg dirs and try again?

**Comment by cmwall** [comment]
@evanphx  Issue was resolved on my end by removing the package and pulling from Github. I think I downloaded an out-of-date release (or possibly a Mac-only release).

Everything works well now :+1:

**Comment by hron84** [comment]
@evanphx of course not! Go is installed to `/usr/bin/go`, as it is a system-provided package. Since both `/usr/bin` and `/usr/local/bin` is in path, it should not be an issue. Maybe you hard-coded some paths for Go?

**Comment by hron84** [comment]
Btw, I re-cloned the git repo and it seems working for me now. At some point you fixed something for me.
