### ISSUE TITLE
`Error listening: accept tcp 0.0.0.0:0: accept: invalid argument` El Capitan - 10.11.6

### ISSUE THREAD

**Issue by ChrisLusted** [puma/puma-dev#33]
I have run through the setup with homebrew but the my sites never seem to  load. 

Running  `tail -f ~/Library/Logs/puma-dev.log` shows this output
```
2016/08/03 14:50:32 Error listening: accept tcp 0.0.0.0:0: accept: invalid argument
* Directory for apps: /Users/kip/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: inherited from launchd
* HTTPS Server port: inherited from launchd
! Puma dev listening on http and https
2016/08/03 14:50:42 Error listening: accept tcp 0.0.0.0:0: accept: invalid argument
```

Any ideas what i've done wrong?

Thanks

**Comment by JustinAiken** [comment]
I had that same issue in #30 - a restart fixed it for me

**Comment by ChrisLusted** [comment]
Ignore, was me being stupid! A restarting and making sure apache was turned off fixed the issue

**Comment by lucasocon** [comment]
Works for me turning off apache.
