### ISSUE TITLE
.test domain by default

### ISSUE THREAD

**Issue by kenn** [puma/puma-dev#36]
Since Google is now in possession of the `.dev` domain, I believe `.test` domain is more acceptable to anyone as it's reserved for the use cases exactly like this?

https://iyware.com/dont-use-dev-for-development/

I know it is configurable, but I think the default / convention is key for those who work in multiple projects. What do you think?

**Comment by glennfu** [comment]
I love my .dev domains, but that seems to make a really good case for moving away from it. I say .test sounds like the next best option.

**Comment by evanphx** [comment]
Puma-dev is young enough that it shouldn't be too big of an issue to switch entirely.

**Comment by coreyward** [comment]
Google's stated intentions re: `.dev` are to use it internally, similar to how Pow and Puma-Dev use it today, presumably. Unless you work at Google, `.dev` should remain safe to map back to localhost.

**Comment by kenn** [comment]
@coreyward I wouldn't ignore 57,000 Googlers though... I assume their use of `.dev` is not 100% compatible with the way how we do it here.

**Comment by coreyward** [comment]
@kenn Sure, but if we're splitting hairs here, Google doesn't use Ruby. There are a few mentions of engineers using Ruby for a prototype, but that's it. So maybe 1% of Google employees use Ruby in any form, and some fraction of them might use a rack server, and some fraction of them might use Puma. Assuming adoption of puma-dev goes as well as Pow, we might be looking at around 20 people at Google if we're being very generous.  ¯\_(ツ)_/¯

**Comment by kenn** [comment]
@coreyward I feel bad about penalizing someone for being minorities to save 1 character length, that's all. It's configurable, so you can continue to use `.dev` either way - but the default is about setting the tone and doing the right thing.

**Comment by coreyward** [comment]
@kenn Sure, but `.test` isn't recommended in the link you shared, `.localhost` is.

**Comment by kenn** [comment]
@coreyward RFC-6761 does not specify the use of the `test` domain. It just guarantees that there is no central authority for the domain, which is the point in our use case here.

**Comment by paracycle** [comment]
In support for @kenn's proposal the [relevant section](https://tools.ietf.org/html/rfc2606#section-2) from RFC-2606, which RFC-6761 builds upon and references, clearly states:

>      To safely satisfy these needs, four domain names are reserved as
>      listed and described below.
> 
>                    .test
>                 .example
>                 .invalid
>               .localhost
> 
>       ".test" is recommended for use in testing of current or new DNS
>       related code.
> 
>       ".example" is recommended for use in documentation or as examples.
> 
>       ".invalid" is intended for use in online construction of domain
>       names that are sure to be invalid and which it is obvious at a
>       glance are invalid.
> 
>       The ".localhost" TLD has traditionally been statically defined in
>       host DNS implementations as having an A record pointing to the
>       loop back IP address and is reserved for such use.  Any other use
>       would conflict with widely deployed code which assumes this use.

So using `.test` as the default top-level domain sounds like the reasonable and correct thing to do.

**Comment by coreyward** [comment]
@paracycle Thanks for sharing the RFC text directly. Note that `.test` is not recommended for loopback, but in “testing of […] DNS related code”. The appropriate TLD for self-referencing (loopback) is `.localhost`. 

I'm in favor of either switching to `.localhost` to be in compliance with the recommendations set forth by the RFCs, or continuing to use `.dev` until such a time that a non-hypothetical issue arises. I don't think that using `.test` is a good idea: it's in conflict with the RFC, communicates the wrong thing, and can conflict with actual DNS testing.

**Comment by kenn** [comment]
The usage definition in RFC is vague at best. Actually we could say it's kinda DNS related (if we consider local resolver a part of name services), as its use (instead of raw IP `127.0.0.1` directly) can be tied to multiple domain specific cookies.

For instance, two projects (e.g. `foo.test` and `bar.test`) can have separate cookie realms, password manager, etc. based on the domain, which is very useful.

Practically speaking, the real question here is which we trust more, Google's promise that they won't use `.dev` or RFC's promise that `.test` is never used. To be honest how many Ruby devs these days need local DNS testing with the `.test` domain? I have played around with BIND since 18 years ago (wow), I never needed such a thing, so I believe the point is moot. :)

Probably no one wants `.localhost` - it's just too verbose for the purpose, so let's not digress with it.

**Comment by evaryont** [comment]
This has renewed importance with the recent addition of `.dev` to the HSTS list. Though puma-dev does already set up a HTTPS CA so it shouldn't cause any issues, Google's actions are now affecting users outside of the organization.

**Comment by Exelord** [comment]
There's also one problem with `.localhost` (I know about Chrome).
If your apps will use domain-wide cookies they won't be shared between the `.localhost` subdomains- as they call "for security reasons". So, it will cut out cookies abilities.

**Comment by kenn** [comment]
For the record, I've switched every project to the `.test` domain over a year ago, and seen any problems.

> Practically speaking, the real question here is which we trust more, Google's promise that they won't use .dev

We've already witnessed the Google's promise is broken, I wouldn't be surprised if we see more exercise of their power over `.dev` affecting us. It's time to cut the dependency on it.

**Comment by evanphx** [comment]
It was done! v0.12 changes this.
