### ISSUE TITLE
Unsupported protocol scheme for proxying port on localhost

### ISSUE THREAD

**Issue by eturk** [puma/puma-dev#37]
I'm trying to proxy `http://localhost:4000` to `site.photography.dev` using the file `~/.puma-dev/site.photography` and I keep getting this in the logs:

```
http: proxy error: unsupported protocol scheme:
```

I've tried several different contents of `~/.puma-dev/site.photography`:

- `localhost:4000`
- `http://localhost:4000`
- `127.0.0.1:4000`
- `4000`

And I've received the same error for each different line. I don't know if it's that I'm using the incorrect content or if this is a bug, but any assistance would be helpful.

**Comment by evanphx** [comment]
That must be a bug. I'll have a look.

**Comment by evanphx** [comment]
Hm, just having `4000` should work fine. Otherwise you need the full url which should also work...

**Comment by eturk** [comment]
I uninstalled the service with `puma-dev -uninstall` and reinstalled it with `puma-dev -install` and now it's working. Must've just needed a restart, but this still might be a bug, I think.

**Comment by evanphx** [comment]
I haven't been able to verify the bug, so if it crops up again please open a new issue.

**Comment by paracycle** [comment]
I was having the exact same problem on my OSX (or should I call it macOS) install and uninstall/install fixed it for me too.

**Comment by paracycle** [comment]
Btw, the `README` states to run:
```
echo 10.3.1.2:9292 > ~/.puma-dev/awesome-elsewhere
```
but that was resulting in this being logged:
```
* Generated proxy connection for 'spog' to ://
```

I guess the scheme prefix is mandatory (in which case the `README` is not complete) and failing to include it puts the server in a state it can't recover from.

**Comment by evanphx** [comment]
That's quite right. I should add support for host:port.

**Comment by vassyz** [comment]
Uninstalling didn't fix it for me, I'm still getting `http: proxy error: unsupported protocol scheme:`.

**Comment by joegaudet** [comment]
I am seeing the same issue: 

 Generated proxy connection for 'concierge.food' to ://

Which obviously won't work.
