### ISSUE TITLE
xip.io support

### ISSUE THREAD

**Issue by glennfu** [puma/puma-dev#38]
Normally with Pow, http://myapp.192.168.1.3.xip.io loads up http://myapp.dev, which is very useful for testing on a connected iOS device. xip.io was built by the creators of Pow to be used with it so I figure if puma-dev is supposed to replace Pow, it would be really handy if you could support this as well.

Right now I'm running the v0.7 release and when I visit http://myapp.192.168.1.3.xip.io I see "unknown app" in a 500 response. Visiting http://myapp.dev works just fine.

**Comment by evanphx** [comment]
I'll add this into the next release.

**Comment by koenpunt** [comment]
As an alternative you could use ngrok, which creates a network tunnel to your local machine, instead of DNS trickery. I never looked back at xip.io after learning about ngrok. 
See https://ngrok.com/
