### ISSUE TITLE
Unable to configure OS X resolver: open /etc/resolver/dev: permission denied

### ISSUE THREAD

**Issue by csexton** [puma/puma-dev#39]
Fresh install of puma-dev and I was getting the following error in the logs. Same log message every 10 seconds as `launchd` would respawn it:

```
tail -1 ~/Library/Logs/puma-dev.log
2016/08/04 14:18:21 Unable to configure OS X resolver: open /etc/resolver/dev: permission denied
```

I installed via homebrew, and ran the install. Something like this:

```
brew install puma/puma/puma-dev
puma-dev -install
```

Got the root password prompt, and everything.

Still the local apps were timing out.

To work around this issue, I bestowed the most evilest of permissions on the file. The permissions of the beast. 

```
sudo chmod 666 /etc/resolver/dev
```

Now everything is working and happy. But that hack seems wrong. Unholy even. 👹

**Comment by attilagyorffy** [comment]
I do not represent the puma group in any way but I'm trying to see if I can help with the issue you may be having.

Sounds like the permissions on the `/etc/resolvers` directory haven't been modified prior to launchd trying to run the service. You need to run `sudo puma-dev -setup` that should prepare this modification. It is also mentioned in the README, maybe you just missed this step. Does this help?

**Comment by subakva** [comment]
Can't speak for @csexton, but I ran through all the steps as outlined in the README.

When I first ran ```puma-dev -setup``` it appears to have updated the ownership of the ```/etc/resolvers``` directory, but ```/etc/resolvers/dev``` was still owned by root.

I deleted the root-owned ```dev``` file and let re-ran ```puma-dev -setup```, which created a new version with the correct ownership/permissions.

No more errors, no more unholy permissions.

**Comment by csexton** [comment]
I was coming from pow. Seems I should have ran the pow uninstaller to clear `/etc/resolver/dev`

```
curl get.pow.cx/uninstall.sh | sh
```

Then follow up with these steps:

```
brew install puma/puma/puma-dev
sudo puma-dev -setup
puma-dev -install
```

I did notice that `puma-dev -setup` will set the directory permissions on `/etc/resolvers`, is that needed? Seems like it might be better to create the file at setup time instead of runtime.

I am up and running now, happy to close this issue unless you want to keep it open to deal with the issued of installing along side pow.

**Comment by attilagyorffy** [comment]
@csexton @subakva I've created a patch, would you mind giving it a try and sending feedback? If you want to regenerate the pow files, you can use `sudo pow --install-system` and then check whether my patch works.

**Comment by csexton** [comment]
@attilagyorffy I spent some time trying to figure out how to build `puma-dev` with no luck. I think I was getting close -- even started to learn what a 'gb' was. But, alas, I am stumped. 

Would you be able to post a binary release on your fork of the repo? Happy to test if I can figure out how.

**Comment by attilagyorffy** [comment]
@csexton I've issued a PR and there's more discussion there: https://github.com/puma/puma-dev/issues/34 In short, it probably won't be accepted as @evanphx is thinking of fixing the issue differently. I'm happy to upload a binary for the time being, but all you need to do is to change the permissions on `/etc/resolvers/dev` so that `puma-dev` can write to them during `puma-dev -install` (using a simple `chown`)
