### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by sachse** [puma/puma-dev#4]
Being able to install puma-dev through Homebrew would be great. I'd be happy to try creating a Homebrew formula that would make this possible, if we could get a release with the changes from #3 in the .tar.gz file.

**Comment by evanphx** [comment]
An excellent idea! I'll do that today.

**Comment by NickLaMuro** [comment]
Well, here is a super janky attempt at simplistic Homebrew formula that you can install manually:

```ruby
class PumaDev < Formula
  desc "A tool to manage rack apps in development with puma"
  homepage "https://github.com/puma/puma-dev"
  url 'https://github.com/puma/puma-dev.git', :using => :git
  version '0.1.0' # I am taking a stab in the dark with this one here

  depends_on "go" => :build

  def install
    ENV['GOPATH']=buildpath
    system "go", "get", "github.com/constabulary/gb/..."
    system "bin/gb build cmd/puma-dev"
    bin.install "bin/puma-dev"
  end

  test do
    require 'open3'
    puma_dev_bin = "#{bin}/puma-dev"
    ::Open3.popen3("#{puma_dev_bin} -h") do |_, _, stderr|
      assert_equal "Usage of #{puma_dev_bin}:", stderr.readlines.first.strip
    end
  end
end
```

You can just save that as `puma_dev.rb` somewhere on your filesystem and run `brew install /path/to/puma_dev.rb` and it #shouldIReallyHopeItWorksForSomeoneBesidesMe work.  This uses the `GitDownloadStrategy`, and I am not sure if the homebrew team likes using that in official formula repo, so this probably would not be accepted there.  You are welcome to use it if does the trick though.

**Comment by sachse** [comment]
Turns out Homebrew doesn't want repositories that are newer than 30 days. I'll submit a PR once it's possible.

**Comment by evanphx** [comment]
Ok, done! `brew install puma/puma/puma-dev`!

**Comment by evanphx** [comment]
The formula is over here: https://github.com/puma/homebrew-puma/blob/master/puma-dev.rb
