### ISSUE TITLE
Error listening: accept tcp 0.0.0.0:0: accept: invalid argument

### ISSUE THREAD

**Issue by scrogson** [puma/puma-dev#40]
Hey there,

Thanks for creating this project. I'm a core contributor on the Phoenix Framework and working with Channels in dev has been a pain with `pow`, so I'm looking forward to using this! 

Unfortunately, I'm having trouble getting this to work. I've uninstalled `pow` and copied over my `~/.pow` directory to `~/.puma-dev`. All of my files are using the port proxy style configuration. I installed `puma-dev` via `brew` so I'm running `0.7`.

After installing, I ran the following:

```
sudo puma-dev -setup
puma-dev -install
```

When tailing the log file I just see this every 10 secs:

```
* Directory for apps: /Users/scrogson/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: inherited from launchd
* HTTPS Server port: inherited from launchd
! Puma dev listening on http and https
2016/08/04 15:06:09 Error listening: accept tcp 0.0.0.0:0: accept: invalid argument
```

Not sure what to check next.

**Comment by evanphx** [comment]
My guess is you have something already listening on port 80 or 443?

**Comment by scrogson** [comment]
Ok, got it! I had to stop `apache` and make `/etc/resolver/dev` world writeable. 👍

**Comment by beechnut** [comment]
I recently had this issue, and couldn't see anything significant with `sudo lsof -i :80`. A restart solved it.
