### ISSUE TITLE
When the rails application failed to load on boot, I have to reload the agent.

### ISSUE THREAD

**Issue by koenpunt** [puma/puma-dev#43]
When I have file using a non-existing class (in my case `ActiveModel::Serializer`, due to not having it in my `Gemfile` yet), and I try to load the application, I see in the logs the app crashed:

```
 ! Unable to load application: NameError: uninitialized constant ActiveModel::Serializer
 bundler: failed to load command: puma (/Users/koenpunt/.rbenv/versions/2.2.2/bin/puma)
... full trace here ...
```

But puma-dev can't recover from this by itself, and to get it running again I have unload and load the agent.

```
launchctl unload ~/Library/LaunchAgents/io.puma.dev.plist
launchctl load ~/Library/LaunchAgents/io.puma.dev.plist
```

Would be nice if the server could catch and recover from this by presenting the browser with a basic error

**Comment by evanphx** [comment]
This has been fixed in the recent rework of the app boot logic.

**Comment by koenpunt** [comment]
In the 0.8 version the error has changed, but I still have to reload the agent when an error occurs.

And in the log there no sign of the ruby error, only a socket error:

```
2016/08/09 10:43:26 http: proxy error: dial unix /some/path/tmp/puma-dev-6590.sock: connect: connection refused

**Comment by koenpunt** [comment]
Some strange behavior, after a few reloads it now displays `unexpected exit` in the browser, which is better, and I no longer have to reload the agent.

Still would be nice to see the stacktrace in the browser as well.
