### ISSUE TITLE
Unable to install into system: exit status 1

### ISSUE THREAD

**Issue by rilwans** [puma/puma-dev#46]
Getting this Error when run puma-dev -install

Setup dev domains:
  sudo puma-dev -setup

Install puma-dev as a launchd agent (required for port 80 usage):
  puma-dev -install
==> Summary
🍺  /usr/local/Cellar/puma-dev/0.7: 2 files, 10.4M, built in 0 seconds
 ✝ ~  sudo puma-dev -setup
Password:
* Configuring /etc/resolver to be owned by olabode
 ✝ ~  puma-dev -install
2016/08/06 14:00:26 Unable to install into system: exit status 1

**Comment by evanphx** [comment]
Your report is quite confusing. Can you gist the output of running `puma-dev -install`?

**Comment by jcarlos7121** [comment]
im getting the same, the output for my puma-dev -install is:

```
sh-3.2# sudo puma-dev -install
* Use '/usr/local/Cellar/puma-dev/0.8/bin/puma-dev' as the location of puma-dev
2016/08/09 12:53:53 Unable to install into system: open /var/root/Library/LaunchAgents/io.puma.dev.plist: no such file or directory
```

**Comment by evanphx** [comment]
@jcarlos7121 You don't run `-install` as root, that's why. Run it as your regular user.

**Comment by kapowaz** [comment]
I get the same result when trying to run `-install` — and I’m _not_ running as root:

```bash
bdarlow@pinkman:~$ sudo puma-dev -setup
Password:
* Configuring /etc/resolver to be owned by bdarlow
bdarlow@pinkman:~$ puma-dev -install
2016/08/10 16:54:26 Unable to install into system: exit status 1```

**Comment by evanphx** [comment]
This should be fixed by the recent change to generate certs via go directly in setup. Please open a new issue if not.
