### ISSUE TITLE
HTTPS support on OSX El Capitan FireFox and iOS turbolinks-rails

### ISSUE THREAD

**Issue by glennfu** [puma/puma-dev#47]
Here's what I'm seeing in my puma-dev log:

    * Directory for apps: /Users/Glenn/.puma-dev
    * Domains: dev
    * DNS Server port: 9253
    * HTTP Server port: inherited from launchd
    * HTTPS Server port: inherited from launchd
    ! Puma dev listening on http and https
    ! Booting app 'mygame' on socket /Users/Glenn/.puma-dev/mygame/tmp/puma-dev-333.sock
    mygame[1769]: bash: no job control in this shell
    mygame[1769]: stty: stdin isn't a terminal
    mygame[1769]: stty: stdin isn't a terminal
    mygame[1769]: RVM loading: /Users/Glenn/.rvm/environments/ruby-2.3.0
    mygame[1769]: Puma starting in single mode...
    mygame[1769]: * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
    mygame[1769]: * Min threads: 0, max threads: 5
    mygame[1769]: * Environment: development
    mygame[1769]: * Listening on unix:/Users/Glenn/.puma-dev/mygame/tmp/puma-dev-333.sock
    mygame[1769]: Use Ctrl-C to stop
    ! App 'mygame' booted
    2016/08/08 13:58:43 http2: server: error reading preface from client 127.0.0.1:49506: remote error: unknown certificate authority
    2016/08/08 13:59:59 http: TLS handshake error from 127.0.0.1:49623: EOF

This is after loading up the url in FireFox. I see "Your connection is not secure. The owner of mygame.dev has configured their website improperly".

Also after reading #26 I figured I'd try some suggestions there. Like running `puma-dev` directly and opening "https://mygame.dev:9283" shows this in the console:

     → puma-dev
    * Directory for apps: /Users/Glenn/.puma-dev
    * Domains: dev
    * DNS Server port: 9253
    * HTTP Server port: 9280
    * HTTPS Server port: 9283
    ! Puma dev listening on http and https
    2016/08/08 14:06:35 http2: server: error reading preface from client 127.0.0.1:49731: remote error: unknown certificate authority

Now Safari shows that the certificate is valid. However if I connect to my Rails + Turbolinks app via a WKWebView in iOS9, I see:

    "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk." UserInfo={error=Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk." UserInfo={NSUnderlyingError=0x7fbc40f08b20 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk." UserInfo={_kCFStreamErrorDomainKey=3, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9813, _kCFStreamPropertySSLClientCertificateState=0, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk., NSErrorFailingURLKey=https://mygame.dev/, NSErrorFailingURLStringKey=https://mygame.dev/, _kCFStreamErrorCodeKey=-9813}}, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSErrorPeerCertificateChainKey=<CFArray 0x7fbc40f08ab0 [0x10bfe8a40]>{type = mutable-small, count = 1, values = (
    	0 : <cert(0x7fbc40f08fc0) s: mygame.dev i: Puma-dev CA>
    )}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk., _WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x7fbc42015ee0>, NSErrorFailingURLKey=https://mygame.dev/, NSErrorClientCertificateStateKey=0, NSErrorFailingURLStringKey=https://mygame.dev/}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mygame.dev” which could put your confidential information at risk.}

**Comment by evanphx** [comment]
You probably need to add the puma-dev CA to firefox to be trusted, since it doesn't use the Apple keychain to do so. The CA file is at `~/Library/Application\ Support/io.puma.dev/cert.pem`.

**Comment by glennfu** [comment]
It's easy enough to just click "Add Exception" in FireFox, but I have no idea how to resolve it for iOS / Xcode.

**Comment by NonaSuomy** [comment]
Just to note, I was first trying to get the plugin working with Chrome which I had no luck on, so then I thought I should try firefox. I didn't realize that you had to run the plugin interface again in the browser (as I already had the bridge installed) to get this cert nfo to popup just thought it would be universal for the platform you are working with, might want to handle this differently as I didn't know what to do until I found this issue post. Then re-ran the getting started stuff and then it worked great in FF. :+1:

**Comment by lulalala** [comment]
I tried to add the cert.pem in Firefox, but it fails saying:

> This personal certificate can't be installed because you do not own the corresponding private key which was created when the certificate was requested`

![20170369_170327-capturfiles](https://cloud.githubusercontent.com/assets/11168836/23838454/d3280142-07d0-11e7-915c-7350d1a41113.png)

When I do the usual "Add Exception" in Firefox, it never remembers that after restart.

Do I have to do something with the cert?

**Comment by rlue** [comment]
@lulalala: It's probably a little too late for this, but you were probably trying to import the key under the wrong category. It should be imported as an "Authority", not as one of "Your certificates".

"Add exception" only works on a one-time basis because puma-dev generates a new certificate (based on the same `cert.pem` CA certification file) each time it's launched.
