### ISSUE TITLE
Disconnected from logs

### ISSUE THREAD

**Issue by glennfu** [puma/puma-dev#49]
I had `~/Library/Logs/puma-dev.log` open in TextMate for debugging issues, and everything was going fine, until I decided "oh let me clear the log so I can see better what happens next". So I idd ctrl+a, backspace, save. Then no more entries were written to the log. I tried also running `pkill -USR1 puma-dev` and restarting the app server but still nothing is getting written. What can I do to reconnect puma-dev to the log?

**Comment by glennfu** [comment]
Also speaking of logs... I did a `brew uninstall puma-dev` off the 0.7 release so that I could then manually install puma-dev 0.8 since that update hasn't shown up on Homebrew yet. I noticed nothing in the logs ever seem to appear about the version. It might be nice for puma-dev to report its version to help make sure I'm running the one I expect and not a stale one in memory.

**Comment by evanphx** [comment]
I forgot to push the update to homebrew, it's live now.

I'll have to debug the log issue, I'm curious what you did after you you deleted all the lines. How did you try to read it? What about if you just run `cat` on the file, is there any contents that way?

**Comment by glennfu** [comment]
TextMate normally automatically refreshes the file to show changes instantly, giving you the same kind of feel of a --tail. I just tried `cat ~/Library/Logs/puma-dev.log` and it prints nothing. The file is empty still!

**Comment by evanphx** [comment]
My guess is that what happened is tat when you saved Textmate, you actually wrote a new file rather than truncating the existing one. puma-dev still has a handle open to the old log file but the filesystem isn't showing it.

If you restart puma-dev entirely (`pkill puma-dev`) I'm betting the log will start to work again. And in which case, don't use textmate to "truncate" the log 😄.

**Comment by glennfu** [comment]
I don't think that sounds right. I frequently view logs this way, and no other application, including logs from Rails, or Pow, or anything else I've ever tried really, have suffered from this problem. 

I also stated in the OP that I called `pkill -USR1 puma-dev` and restarted my app and the logs did not resume. If I omit the `-USR1` do you think that would be better?

**Comment by evanphx** [comment]
If you kill it entirely it will restart and should work. I'll have to investigate because the log is actually written and maintained by launchd, not puma.
