### ISSUE TITLE
Incompatible with ngrok for connection tunneling

### ISSUE THREAD

**Issue by danielwestendorf** [puma/puma-dev#50]
[ngrok](https://ngrok.com/) is a HTTP tunneling tool for accessing hosts behind NAT by tunneling the network connection through a locally run script. This allows me to test webhook locally.

I have puma-dev functioning just fine so that I can access the app via my browser by navigating to 

`$ ngrok http railsapp.dev:80` returns a 500 "unknown app" when using puma-dev.

`$ ngrok http localhost:3000` works fine with the same app when `$ rails s` is used.

Running latest version puma-dev's as a service on OSX 10.10. Installed via `sudo puma-dev -setup`

I'm not sure if this is a problem with puma-dev or ngrok. I didn't have any problems with pow with this same configuration, so I'm starting here. How can I help diagnose the problem?

**Comment by evanphx** [comment]
You need to pass `--host=header=railsapp.dev` to ngrok so that the Host header is correct. This is documented by ngrok here: https://ngrok.com/docs#host-header

I'm not sure how this would work with pow out of the box without also using `--host-header`.

**Comment by danielwestendorf** [comment]
Awesome working as expected with that option, thanks!🤘🏻 🌟 🍆 🎉

**Comment by tadman** [comment]
Correction: It's `--host-header=railsapp.dev` (or `.test` in newer puma-dev) not `-host=header`.
