### ISSUE TITLE
puma-dev restarts with .dev instead of .test I installed with

### ISSUE THREAD

**Issue by jlw** [puma/puma-dev#55]
I installed puma-dev last week and couldn't get it working. I tracked it down today to Google's ownership of .dev and resolving addresses to 127.0.53.53, so I don't know why puma-dev uses .dev (yes, pow compatibility, except it doesn't work for anyone who didn't already have pow running).

I uninstalled puma-dev, re-installed specifying `.test` instead of `.dev`, tested it and did other things. When I came back, I couldn't get to #{site}.test - using `ps` I discovered that puma-dev had restarted on the `.dev` TLD. This is a bug - now I'm sitting around wasting time trying to figure out where the puma-dev launchd config is so I can fix this laziness.

**Comment by evanphx** [comment]
@jlw Are you running on OS X or linux? Puma-dev does absolutely support the .dev domain by modifying `/etc/resolver` to point the dev tld to be managed by puma-dev. The `puma-dev -install` step is what sets that up.

@jlw Puma-dev will use whatever domains are specified on the command line, which is controlled by what you pass with `-d`. I suggest you run `puma-dev -unistall` then `puma-dev -d test -install` will be sure that it uses .test.

I don't know where the bug would be here since it uses whatever settings you pass it.

**Comment by jlw** [comment]
@evanphx - I am on OS X (10.10.5). I say that .dev doesn't work for me because I tried it first with no success, then switched to .test and had an immediate success. Shortly after getting things running on .test, I could no longer connect - here is an unaltered section from my bash shell showing the problem:

```
~/Sites/simmons/bondholders [redesign] jer $ puma-dev -install -d test
* Use '/usr/local/Cellar/puma-dev/0.7/bin/puma-dev' as the location of puma-dev
* Installed puma-dev on ports: http 80, https 443
~/Sites/simmons/bondholders [redesign] jer $ ps aux | grep puma
jer             28699   0.0  0.0  2443012    708 s008  S+    3:20PM   0:00.00 grep puma
jer             28689   0.0  0.0 573446468   6504   ??  S     3:20PM   0:00.01 /usr/local/Cellar/puma-dev/0.7/bin/puma-dev -launchd -dir ~/.puma-dev -d test -timeout 15m0s
~/Sites/simmons/bondholders [redesign] jer $ ps aux | grep puma
jer             28892   0.0  0.0  2452228    728 s008  S+    3:30PM   0:00.00 grep puma
jer             28802   0.0  0.0 573439684   6804   ??  S     3:20PM   0:00.04 /usr/local/Cellar/puma-dev/0.7/bin/puma-dev -launchd -dir ~/.puma-dev -d dev -timeout 15m0s
~/Sites/simmons/bondholders [redesign] jer $ puma-dev -h
```

Notice that the process switched and changed TLDs. I was not making any other changes in other shell sessions. To fix the problem, I edited the launchd config to change the TLD from dev to test, and reloaded the launchd config:

```
~/Sites/simmons/bondholders [redesign] jer $ launchctl unload ~/Library/LaunchAgents/io.puma.dev.plist 
~/Sites/simmons/bondholders [redesign] jer $ launchctl load ~/Library/LaunchAgents/io.puma.dev.plist 
```

As far as I can tell, at least one or two things happened incorrectly:

1. `puma-dev -d test -install` did not write the correct LaunchAgent .plist (line 14 had the "dev" string to pass to the "-d" argument instead of "test")
2. and maybe `puma-dev -uninstall` did not correctly remove the original LaunchAgent .plist

There easily could be other factors, especially with .dev not working for me (its been ages since I've had a clean OS install), but I would hope that the problem with the LaunchAgent .plist should be fairly easy to track down.

**Comment by evanphx** [comment]
Can you please confirm if '-install' writes '-d test' to the plist in the
latest release (0.8).

**Comment by jlw** [comment]
@evanphx - Yes it did - thank you.
