### ISSUE TITLE
fork: Resource temporarily unavailable occurring since installing

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#56]
Since installing puma-dev, apart from my development environment being better than it's ever been, I have noticed occasionally that I get:

`fork: Resource temporarily unavailable` when trying any operation in Terminal. I first noticed it when tabs started crashing in Chrome.

It could be something unrelated, but a quick google for that error leads to articles about `launchd` so it seems a bit co-incidental.

I have no idea what's causing it ... a memory leak perhaps? I'm not all that sure where to start looking. For the most part, unloading and reloading puma-dev using `launchctl` solves it, or just quitting all apps and restarting them.

Could be nothing, but I thought this might tip you off to something that I'm not able to suggest!

**Comment by koenpunt** [comment]
The error has to do with the process limit set on your system. I had the same yesterday, and I think it's puma-dev in combination with Spring, which watches a lot files. Try running `ps aux | grep fsevent_watch` from a terminal, and see if it yields a lot of results.

**Comment by koenpunt** [comment]
> The error has to do with the process limit set on your system.

I'm not saying this is a low limit, just saying it's not a puma-dev error.

**Comment by paulca** [comment]
👍

**Comment by evanphx** [comment]
Have no clue why rails launches billions of fsevent_watch processes and we should probably report it to rails because it's a bit silly.

**Comment by koenpunt** [comment]
For reference, the same happens here: https://github.com/resque/resque/issues/1483

**Comment by beneggett** [comment]
Linking to the Rails issue that explains all this here: https://github.com/rails/rails/issues/26158

A couple helpful commands if you're experiencing this: 

See all the events that are running:
```
ps aux | grep fsevent_watch
```

See how many problems you got ;) 
```
ps aux | grep fsevent_watch | wc -l
```

Kill your problems 💣 

```
pkill -f fsevent_watch
```

See your machine's limit
```
ulimit -u
```

The real answer to solving for now is removing the listen gem and modifying your development.rb to not watch those directories.

**Comment by goalaleo** [comment]
Here's a simple fix that worked for me (running Rails 5 on OS X):

in `development.rb` change `config.file_watcher = ActiveSupport::EventedFileUpdateChecker``
to `config.file_watcher = ActiveSupport::FileUpdateChecker`, and remove following gems:
`listen` and `spring-watcher-listen` <- if using. From other issues it seems like the culprit might be
`rb-fsevent`gem which `listen` depends on.

**Comment by fuzzygroup** [comment]
Thank you, thank you, thank you!  I'm developing a rails app along the lines of service oriented architecture and all the different pieces run as separate http processes. Developing under OSX has been horridly frustrating because I can't ever run all the pieces together.
