### ISSUE TITLE
symlinking is hard

### ISSUE THREAD

**Issue by olivierlacan** [puma/puma-dev#61]
I know, you're laughing, but seriously I can never remember if it's `ln -s` or `ls -n` because abbreviated commands are easy to type and atrociously hard to remember.

More importantly puma-dev knows where the symlink is supposed to live so there's at least half a concern there. 

```shell
$ cd /Users/olivierlacan/Development/oss/blah
$ puma-dev link
* Symlinked /Users/olivierlacan/Development/oss/blah to /Users/olivierlacan/.puma-dev/blah/
* You can now open blah.dev
```

Believe it or not this is the thing I probably used [powder](https://github.com/rodreegez/powder) for the most. No having to remember the `ln` command, no fucking up the order of arguments. Link this thing right here.

Alternatively `link` could take a relative/absolute path argument too.

**Comment by evanphx** [comment]
No problem, I'll add it.
