### ISSUE TITLE
App dying on start

### ISSUE THREAD

**Issue by Vaultman** [puma/puma-dev#62]
I'm unable to boot any application via puma-dev. I'm getting this log message twice for every attempt to load an app.

```
! Booting app 'intranet' on socket /Users/vaultman/.puma-dev/intranet/tmp/puma-dev-89147.sock
intranet[92437]: Puma starting in single mode...
intranet[92437]: * Version 2.15.3 (ruby 2.3.0-p0), codename: Autumn Arbor Airbrush
intranet[92437]: * Min threads: 0, max threads: 5
intranet[92437]: * Environment: development
! Killing 'intranet' (92437)
! Killing 'intranet' (92437)
* App 'intranet' shutdown and cleaned up
! Detecting app 'intranet' dying on start
```

When i just run `puma` in app root, it boots without any problem. I have no custom config.

puma-dev is installed via homebrew.

**Comment by evanphx** [comment]
Hm, for some reason puma-dev decided to stop the app right away. Does this happen everytime you try to access the app?

**Comment by Vaultman** [comment]
Yes, everytime I try to access every single one app. It worked yesterday. Today I `brew upgrade` so I gues something broke in the last version. Reinstalling and restarting didn't help.

**Comment by evanphx** [comment]
The latest release should help understand what is happening. After make a request to the app, run `curl -H "Host: puma-dev" localhost/events` and paste the output. It will tell us the decisions that puma-dev made internally.

**Comment by Vaultman** [comment]
Ok, here is the output

```
{"time":"2016-08-14 11:44:05.652260827 +0200 CEST","event":"app_lookup","path":"/Users/vaultman/.puma-dev/intranet"}
{"time":"2016-08-14 11:44:05.660067321 +0200 CEST","event":"booting_app","app":"intranet","socket":"/Users/vaultman/.puma-dev/intranet/tmp/puma-dev-69585.sock"}
{"time":"2016-08-14 11:44:05.660180236 +0200 CEST","event":"waiting_on_app","app":"intranet"}
{"time":"2016-08-14 11:44:15.662824825 +0200 CEST","event":"idle_app","app":"intranet","last_used":"2562047h47m16.854775807s"}
{"time":"2016-08-14 11:44:15.662869318 +0200 CEST","event":"killing_app","app":"intranet","pid":74872,"reason":"app is idle"}
{"time":"2016-08-14 11:44:15.673245046 +0200 CEST","event":"killing_app","app":"intranet","pid":74872,"reason":"stdout/stderr closed"}
{"time":"2016-08-14 11:44:15.673439018 +0200 CEST","event":"shutdown","app":"intranet"}
{"time":"2016-08-14 11:44:15.67346588 +0200 CEST","event":"dying_on_start","app":"intranet"}
{"time":"2016-08-14 11:44:15.673476551 +0200 CEST","event":"lookup_error","error":"unexpected exit"}
{"time":"2016-08-14 11:44:16.158427651 +0200 CEST","event":"app_lookup","path":"/Users/vaultman/.puma-dev/intranet"}
{"time":"2016-08-14 11:44:16.166133829 +0200 CEST","event":"booting_app","app":"intranet","socket":"/Users/vaultman/.puma-dev/intranet/tmp/puma-dev-69585.sock"}
{"time":"2016-08-14 11:44:16.166220129 +0200 CEST","event":"waiting_on_app","app":"intranet"}
```

It returns the same reason for every app I have.

**Comment by evanphx** [comment]
Wow! Something vey strange is happening the idle calculation. Immediately
after boot it thinks your app has been idle for 2562047h47m!

**Comment by evanphx** [comment]
I think I see the issue. Should have it fixed tonight.

**Comment by manuelmeurer** [comment]
Same issue here... getting `unexpected exit` when I try to access an app that's not yet loaded. After a reload it works.

From the log:

```
! Booting app 'myapp' on socket /Users/manuel/.puma-dev/myapp/tmp/puma-dev-20867.sock
myapp[13014]: bash: no job control in this shell
myapp[13014]: Puma starting in single mode...
myapp[13014]: * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
myapp[13014]: * Min threads: 0, max threads: 5
myapp[13014]: * Environment: development
! Killing 'myapp' (13014)
! Killing 'myapp' (13014)
* App 'myapp' shutdown and cleaned up
! Detecting app 'myapp' dying on start
! Booting app 'myapp' on socket /Users/manuel/.puma-dev/myapp/tmp/puma-dev-20867.sock
myapp[13470]: bash: no job control in this shell
myapp[13470]: Puma starting in single mode...
myapp[13470]: * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
myapp[13470]: * Min threads: 0, max threads: 5
myapp[13470]: * Environment: development
myapp[13470]: * Listening on unix:/Users/manuel/.puma-dev/myapp/tmp/puma-dev-20867.sock
myapp[13470]: Use Ctrl-C to stop
! App 'myapp' booted
```

**Comment by manuelmeurer** [comment]
`curl -H "Host: puma-dev" localhost/events` doesn't work for me, it returns `404 page not found`.

**Comment by evanphx** [comment]
@manuelmeurer You need to upgrade to the latest version have that endpoint available.

**Comment by manuelmeurer** [comment]
Ah yeah right. :)

```
{"time":"2016-08-15 21:37:25.056056627 +0200 CEST","event":"app_lookup","path":"/Users/manuel/.puma-dev/admin.myapp"}
{"time":"2016-08-15 21:37:25.057770305 +0200 CEST","event":"app_lookup","path":"/Users/manuel/.puma-dev/myapp"}
{"time":"2016-08-15 21:37:25.061504095 +0200 CEST","event":"booting_app","app":"myapp","socket":"/Users/manuel/.puma-dev/myapp/tmp/puma-dev-56314.sock"}
{"time":"2016-08-15 21:37:25.062962175 +0200 CEST","event":"waiting_on_app","app":"myapp"}
{"time":"2016-08-15 21:37:25.709769269 +0200 CEST","event":"app_lookup","path":"/Users/manuel/.puma-dev/admin.myapp"}
{"time":"2016-08-15 21:37:35.136706133 +0200 CEST","event":"idle_app","app":"myapp","last_used":"2562047h47m16.854775807s"}
{"time":"2016-08-15 21:37:35.136796549 +0200 CEST","event":"killing_app","app":"myapp","pid":56348,"reason":"app is idle"}
{"time":"2016-08-15 21:37:35.144539697 +0200 CEST","event":"killing_app","app":"myapp","pid":56348,"reason":"stdout/stderr closed"}
{"time":"2016-08-15 21:37:35.144696388 +0200 CEST","event":"shutdown","app":"myapp"}
{"time":"2016-08-15 21:37:35.144722385 +0200 CEST","event":"dying_on_start","app":"myapp"}
{"time":"2016-08-15 21:37:35.144738831 +0200 CEST","event":"lookup_error","error":"unexpected exit"}
{"time":"2016-08-15 21:37:35.144803237 +0200 CEST","event":"lookup_error","error":"unexpected exit"}
{"time":"2016-08-15 21:37:35.594096389 +0200 CEST","event":"app_lookup","path":"/Users/manuel/.puma-dev/admin.myapp"}
{"time":"2016-08-15 21:37:35.594145372 +0200 CEST","event":"app_lookup","path":"/Users/manuel/.puma-dev/myapp"}
{"time":"2016-08-15 21:37:35.598184519 +0200 CEST","event":"booting_app","app":"myapp","socket":"/Users/manuel/.puma-dev/myapp/tmp/puma-dev-56314.sock"}
{"time":"2016-08-15 21:37:35.598315384 +0200 CEST","event":"waiting_on_app","app":"myapp"}
{"time":"2016-08-15 21:37:45.672521673 +0200 CEST","event":"idle_app","app":"myapp","last_used":"2562047h47m16.854775807s"}
{"time":"2016-08-15 21:37:45.672574156 +0200 CEST","event":"killing_app","app":"myapp","pid":56807,"reason":"app is idle"}
{"time":"2016-08-15 21:37:45.68378994 +0200 CEST","event":"killing_app","app":"myapp","pid":56807,"reason":"stdout/stderr closed"}
{"time":"2016-08-15 21:37:45.683927113 +0200 CEST","event":"shutdown","app":"myapp"}
{"time":"2016-08-15 21:37:45.683947812 +0200 CEST","event":"dying_on_start","app":"myapp"}
{"time":"2016-08-15 21:37:45.683961866 +0200 CEST","event":"lookup_error","error":"unexpected exit"}
```

**Comment by olivierlacan** [comment]
@evanphx Hey guess what?! I had thin in my app's Gemfile but no puma. Might be a good idea to recommend that people do add puma to their Gemfile or catch the exception maybe? Because I'm a genius I assumed I was using puma for the app. I was not. 🤓 

`Gem::LoadError: puma is not part of the bundle. Add it to Gemfile.`

**Comment by evanphx** [comment]
@olivierlacan Ha! I should probably add some checks to make sure people have it!

**Comment by moisesnarvaez** [comment]
I solved this running `bundle install`

**Comment by jomarbarnobal** [comment]
anyone fixed on this 'unexpected exit' when running my app in browser 

{"time":"2016-11-16 18:29:52.456428359 +0800 PHT","event":"app_lookup","path":"/Users/binaryarrow/.puma-dev/blog-api"}
{"time":"2016-11-16 18:29:52.552435723 +0800 PHT","event":"booting_app","app":"blog-api","socket":"/Users/binaryarrow/.puma-dev/blog-api/tmp/puma-dev-75301.sock"}
{"time":"2016-11-16 18:29:52.552638155 +0800 PHT","event":"waiting_on_app","app":"blog-api"}
{"time":"2016-11-16 18:30:00.189017105 +0800 PHT","event":"killing_app","app":"blog-api","pid":75311,"reason":"stdout/stderr closed"}
{"time":"2016-11-16 18:30:00.189282222 +0800 PHT","event":"shutdown","app":"blog-api"}
{"time":"2016-11-16 18:30:00.189318346 +0800 PHT","event":"lookup_error","error":"unexpected exit"}
{"time":"2016-11-16 18:30:00.189637718 +0800 PHT","event":"dying_on_start","app":"blog-api"}
{"time":"2016-11-16 18:30:01.289890749 +0800 PHT","event":"app_lookup","path":"/Users/binaryarrow/.puma-dev/blog-api"}
{"time":"2016-11-16 18:30:01.295790552 +0800 PHT","event":"booting_app","app":"blog-api","socket":"/Users/binaryarrow/.puma-dev/blog-api/tmp/puma-dev-75301.sock"}
{"time":"2016-11-16 18:30:01.295977036 +0800 PHT","event":"waiting_on_app","app":"blog-api"}
{"time":"2016-11-16 18:30:04.801936164 +0800 PHT","event":"killing_app","app":"blog-api","pid":75381,"reason":"stdout/stderr closed"}
{"time":"2016-11-16 18:30:04.802255381 +0800 PHT","event":"shutdown","app":"blog-api"}
{"time":"2016-11-16 18:30:04.802295551 +0800 PHT","event":"lookup_error","error":"unexpected exit"}
{"time":"2016-11-16 18:30:04.809150162 +0800 PHT","event":"dying_on_start","app":"blog-api"}

**Comment by jbosse** [comment]
I get the same error @jomarbarnobal

**Comment by jbosse** [comment]
{"time":"2017-03-30 21:10:23.574230104 -0400 EDT","event":"app_lookup","path":"/Users/jbosse/.puma-dev/perp"}
{"time":"2017-03-30 21:10:23.578226019 -0400 EDT","event":"booting_app","app":"demoapp","socket":"/Users/jbosse/.puma-dev/demoapp/tmp/puma-dev-79424.sock"}
{"time":"2017-03-30 21:10:23.578322284 -0400 EDT","event":"waiting_on_app","app":"demoapp"}
{"time":"2017-03-30 21:10:24.460966897 -0400 EDT","event":"killing_app","app":"demoapp","pid":79572,"reason":"stdout/stderr closed"}
{"time":"2017-03-30 21:10:24.461023305 -0400 EDT","event":"shutdown","app":"demoapp"}
{"time":"2017-03-30 21:10:24.461036965 -0400 EDT","event":"lookup_error","error":"unexpected exit"}
{"time":"2017-03-30 21:10:24.461053701 -0400 EDT","event":"dying_on_start","app":"demoapp"}

**Comment by jbosse** [comment]
@jomarbarnobal I managed to resolve my issue by adding a .powenv file in my Rails root.
I had a similar problem with pow when using rvm to manage ruby versions and this fixed that.

```ruby
# detect `$rvm_path`
if [ -z "${rvm_path:-}" ] && [ -x "${HOME:-}/.rvm/bin/rvm" ]
then rvm_path="${HOME:-}/.rvm"
fi
if [ -z "${rvm_path:-}" ] && [ -x "/usr/local/rvm/bin/rvm" ]
then rvm_path="/usr/local/rvm"
fi

# load environment of current project ruby
if
  [ -n "${rvm_path:-}" ] &&
  [ -x "${rvm_path:-}/bin/rvm" ] &&
  rvm_project_environment=`"${rvm_path:-}/bin/rvm" . do rvm env --path 2>/dev/null` &&
  [ -n "${rvm_project_environment:-}" ] &&
  [ -s "${rvm_project_environment:-}" ]
then
  echo "RVM loading: ${rvm_project_environment:-}"
  \. "${rvm_project_environment:-}"
else
  echo "RVM project not found at: $PWD"
fi

```

**Comment by jgervin** [comment]
I am having the same issue but using Rbenv.  I have set Rbenv to local 1.9.3 but the app immediatley crashes and the browser says from /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'

Not sure why it is using ruby 2.3.1 as ruby versions says project directory is set to 1.9.3

statrubytwotwo jn$ curl -H "Host: puma-dev" localhost/events
{"time":"2018-11-28 16:48:36.558649141 -0600 CST m=+1.842019417","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.56016005 -0600 CST m=+1.843530082","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.56042688 -0600 CST m=+1.843796869","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 16:48:36.560697991 -0600 CST m=+1.844067936","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.563621524 -0600 CST m=+1.846990997","event":"app_lookup","path":"/Users/jn/.puma-dev/localhost"}
{"time":"2018-11-28 16:48:36.566312331 -0600 CST m=+1.849681369","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.566653184 -0600 CST m=+1.850022167","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 16:48:36.566922009 -0600 CST m=+1.850290948","event":"app_lookup","path":"/Users/jn/.puma-dev/default"}
{"time":"2018-11-28 16:48:36.567388078 -0600 CST m=+1.850756942","event":"unknown_app","name":"localhost","host":"localhost"}
{"time":"2018-11-28 17:11:33.714593989 -0600 CST m=+1378.966720495","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:11:33.745253605 -0600 CST m=+1378.997380581","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:11:33.755257474 -0600 CST m=+1379.007384603","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:35.905097341 -0600 CST m=+1381.157257426","event":"killing_app","app":"statrubytwotwo","pid":15392,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:11:35.910976285 -0600 CST m=+1381.163136460","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:35.911053843 -0600 CST m=+1381.163214019","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:11:35.911306417 -0600 CST m=+1381.163466597","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:37.779555541 -0600 CST m=+1383.031744360","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:11:37.798043921 -0600 CST m=+1383.050233024","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:11:37.798263999 -0600 CST m=+1383.050453105","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:39.681402782 -0600 CST m=+1384.933620755","event":"killing_app","app":"statrubytwotwo","pid":15526,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:11:39.681754835 -0600 CST m=+1384.933972813","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:11:39.681893219 -0600 CST m=+1384.934111200","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:11:39.682519064 -0600 CST m=+1384.934737054","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:22.45541228 -0600 CST m=+1427.708285948","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:22.490191345 -0600 CST m=+1427.743065546","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:22.493597677 -0600 CST m=+1427.746471931","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:24.313665766 -0600 CST m=+1429.566567921","event":"killing_app","app":"statrubytwotwo","pid":15741,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:24.313836024 -0600 CST m=+1429.566738182","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:24.313890622 -0600 CST m=+1429.566792780","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:12:24.314462757 -0600 CST m=+1429.567364924","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:26.426601154 -0600 CST m=+1431.679535698","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:26.436611439 -0600 CST m=+1431.689546136","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:26.436792476 -0600 CST m=+1431.689727176","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:27.675985747 -0600 CST m=+1432.928939444","event":"killing_app","app":"statrubytwotwo","pid":15875,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:27.676132059 -0600 CST m=+1432.929085758","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:27.676165648 -0600 CST m=+1432.929119347","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:12:27.67682828 -0600 CST m=+1432.929781990","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:50.880388784 -0600 CST m=+1456.133698190","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:50.909920214 -0600 CST m=+1456.163230073","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:50.917031594 -0600 CST m=+1456.170341562","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:52.065640798 -0600 CST m=+1457.318968373","event":"killing_app","app":"statrubytwotwo","pid":16053,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:52.065771399 -0600 CST m=+1457.319098976","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:52.065805476 -0600 CST m=+1457.319133053","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:12:52.065980271 -0600 CST m=+1457.319307851","event":"dying_on_start","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:52.568960015 -0600 CST m=+1457.822295305","event":"app_lookup","path":"/Users/jn/.puma-dev/statrubytwotwo"}
{"time":"2018-11-28 17:12:52.575589621 -0600 CST m=+1457.828925013","event":"booting_app","app":"statrubytwotwo","socket":"/Users/jn/.puma-dev/statrubytwotwo/tmp/puma-dev-11735.sock"}
{"time":"2018-11-28 17:12:52.575733689 -0600 CST m=+1457.829069083","event":"waiting_on_app","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:53.657831663 -0600 CST m=+1458.911183645","event":"killing_app","app":"statrubytwotwo","pid":16181,"reason":"stdout/stderr closed"}
{"time":"2018-11-28 17:12:53.658017688 -0600 CST m=+1458.911369673","event":"shutdown","app":"statrubytwotwo"}
{"time":"2018-11-28 17:12:53.658151214 -0600 CST m=+1458.911503201","event":"lookup_error","error":"unexpected exit:\n\t\tfrom /Users/jn/.rbenv/versions/2.3.1/bin/puma:23:in `<main>'\n"}
{"time":"2018-11-28 17:12:53.661413974 -0600 CST m=+1458.914766011","event":"dying_on_start","app":"statrubytwotwo"}

**Comment by ryana** [comment]
For anyone else who runs into this: this happened to me this morning after doing a `brew upgrade` last night. I was getting this error in the `localhost/events` endpoint:

> {"time":"2021-03-02 09:18:02.923514 -0700 MST m=+31513.447021199","event":"killing_app","app":"web","pid":24079,"reason":"stdout/stderr closed"}

Doing a `puma-dev -uninstall` & `puma-dev -install` fixed the problem for me 🤷

**Comment by rromanchuk** [comment]
i got in this state running brew upgrade as well.  just running `puma-dev -install` was enough to kick it out of this state, didn't even have to uninstall fwiw

**Comment by brendon** [comment]
`puma-dev -install` did it for me too. I do remember seeing a note about that pop up in the massive `brew` update I did. I remember using some alternative install settings so hopefully those copy through or do I have to specify them again?
