### ISSUE TITLE
Error installing on OSX 10.11.16 using Homebrew

### ISSUE THREAD

**Issue by joeczucha** [puma/puma-dev#64]
$ brew install puma/puma/puma-dev
    ==> Tapping puma/puma
    Cloning into '/usr/local/Library/Taps/puma/homebrew-puma'...
    remote: Counting objects: 3, done.
    remote: Compressing objects: 100% (2/2), done.
    remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
    Unpacking objects: 100% (3/3), done.
    Checking connectivity... done.
    Error: Invalid formula: /usr/local/Library/Taps/puma/homebrew-puma/puma-dev.rb
    undefined method `sha56' for #<Class:0x007ff83410edc8>
    Error: Cannot tap puma/puma: invalid syntax in tap!

    $ brew update
    Already up-to-date.

    $ brew doctor
    Your system is ready to brew.

    $ brew config
    HOMEBREW_VERSION: 0.9.9
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: 1e76a207b5bfacebee0a7198318230446be8da47
    Last commit: 84 minutes ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 02d33d0daad4b6a9f2932ad8f9f22e6f2cce62b6
    Core tap last commit: 9 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: octa-core 64-bit skylake
    Homebrew Ruby: 2.0.0-p648
    Clang: 7.3 build 703
    Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /Users/joe/.rbenv/shims/ruby => /Users/joe/.rbenv/versions/2.3.1/bin/ruby
    Java: N/A
    OS X: 10.11.6-x86_64
    Xcode: 7.3.1
    CLT: 7.3.1.0.1.1461711523
    X11: 2.7.9 => /opt/X11

Let me know if I can provide any more details.

Thanks in advance :)

**Comment by evanphx** [comment]
Fixed now, sorry about that!
