### ISSUE TITLE
macOS Sierra - go 1.7 includes additional patches for the timeofday stuff.

### ISSUE THREAD

**Issue by idyll** [puma/puma-dev#67]
My understanding is that 1.7RC6 includes additional fixes for macOS.

Once go 1.7 is released puma-dev will need to be compiled with it to maintain compatibility with macOS Sierra.

**Comment by evanphx** [comment]
More than what was fixed in 1.6.3?

**Comment by evanphx** [comment]
@idyll Are you using my official builds or building puma-dev yourself?

**Comment by nathany** [comment]
@evanphx Yes, Go 1.6.3 had a patch for macOS Sierra beta 3, but then it was busted again in macOS Sierra beta 4. Go 1.7 rc6 is patched for that and Go 1.7 will be released shortly and is identical to rc6.

There is a plan to backport the fix to Go 1.4 (used for bootstrapping), but I don't think Go 1.6 will get a backport of the fix.

**Comment by evanphx** [comment]
@nathany Thanks for the info! I'll begin doing 1.7 build as soon as it goes final (hopefully soon).

**Comment by nathany** [comment]
In about 5 minutes. I'm following the progress on Slack. invite.slack.golangbridge.org

**Comment by idyll** [comment]
Yeah sorry @evanphx but we need 1.7 now. :(
Thanks for taking care of this.

**Comment by nathany** [comment]
https://blog.golang.org/go1.7

**Comment by idyll** [comment]
Also, I have bad news about #66 I don't think they are related as I have been building my own puma-dev. I will test once you release an official update though and report back.

**Comment by evanphx** [comment]
@nathany Well wasn't that great timing! I'll have a release out today built with 1.7.

**Comment by evanphx** [comment]
The latest release `v0.10` and all later releases will be built with Go 1.7.
