### ISSUE TITLE
QUESTION: using binding.pry to debug?

### ISSUE THREAD

**Issue by mepatterson** [puma/puma-dev#70]
More of a question/feature thought than a problem...

I tend to build a lot of rails apps that talk to other rails apps. `puma-dev` is *awesome* for letting me have all those things configured to just magically spin up when I need to mess with something that involves the whole mess of intercommunicating apps. 

One of my typical workflows, though, is the use of `binding.pry` while running an app in the foreground to bust in to a place where something is crashing on a particular app. Since `puma-dev` puts all this in the background, there's no way for me to drop into `pry` by adding that binding line to the code on a specific app.

It appears that I can run `puma-dev` in the foreground, but it runs on a different port than where my other apps are configured to find the app I'm currently debugging (they're all configured to find it at `myapp.dev` on port 80).

Is there an easy way to "take over" control of one of the backgrounded apps to pull it to the foreground while I'm debugging without the host/port changing?

**Comment by evanphx** [comment]
Hm. I suspect `binding.pry` depends on the stdin/stdout of the server being a terminal? I could add terminal emulation to the servers on start to make that happen I suppose, but that's a fair bit of code and I'm not certain it's worth it.

Seems like using something like `pry-remote` would be easier and transparent of puma-dev: https://www.bignerdranch.com/blog/debugging-remote-processes-with-pry-remote/

**Comment by mepatterson** [comment]
That looks like an excellent solution. I'll dig in and see if it works as
expected with puma-dev. Thanks!

**Comment by tadassce** [comment]
I can confirm that [pry-remote](https://github.com/mon-ouie/pry-remote) works nicely with puma-dev.

**Comment by holamendi** [comment]
@mepatterson I don't know if this is still relevant for you but I solved this issue by using puma-dev as a proxy to port 3000, then I just run `rails s` as usual and `binding.pry` works just fine.

**Comment by djadma** [comment]
@holamendi 

How can we set proxy in puma-dev

**Comment by kirillplatonov** [comment]
@djadma
1. `echo 3000 > ~/.puma-dev/appname`
2. `pkill -USR1 puma-dev`
3. run `rails s` in app folder
4. visit `appname.test` and it will be proxied to `localhost:3000`

**Comment by vasudharsai** [comment]
@kirillplatonov 
When I run appname.test it doesn't hit the server stack.However if I run appname.test:3000, I'm able to run my app in local env

**Comment by kirillplatonov** [comment]
@vasudharsai that's weird. Check the content of `~/.puma-dev/appname` file and make sure it have `3000` inside.

**Comment by vasudharsai** [comment]
Sure, thanks @kirillplatonov
