### ISSUE TITLE
Make requirement of puma in the Gemfile optional

### ISSUE THREAD

**Issue by jeroenj** [puma/puma-dev#71]
Currently if a Gemfile is present bundler will be used to start puma: https://github.com/puma/puma-dev/blob/bf30b0e959a6fd2ccf19619dbbf762387866b0d4/dev/app.go#L248-L253

Since we don't use puma in production (yet, and it might take some time) we don't have in in the Gemfile by default. We have an agreement to avoid adding any dependencies that are specific (to some developer's) dev flow. In this situation it would come in handy that if a Gemfile is present it is not required to have puma in there.

A rough idea to work around it:

``` diff
- if test -e Gemfile; then
+ if test -e Gemfile && bundle show puma > /dev/null 2>&1; then
```

`bundle show` will result in a non-zero exit-code if the given gem is not part of the dependency tree. I guess it's clean that output is being ignored, unless the surrounding code does not log any of the output?
The only downside to this is that it spawns an extra ruby process for the bundler check and that it's quite slow: 0.5sec-1sec for an app with ~300 dependencies in its dependency tree.
[`bundle show`](http://bundler.io/v1.1/bundle_show.html) has been around since v1.1 which has been released in 2012.

**Comment by evanphx** [comment]
In the event that puma is not available, what should puma-dev do?

**Comment by jeroenj** [comment]
It would fall back to [the last option in the code](https://github.com/puma/puma-dev/blob/bf30b0e959a6fd2ccf19619dbbf762387866b0d4/dev/app.go#L253). It would run puma without the bundler context.

**Comment by rmm5t** [comment]
The associated PR looks like a solid, clean addition to puma-dev. Any chance it will be merged and part of a new release relatively soon?  I am in the process of leaving pow for puma-dev while maintaining dozens of different projects. I'm sure many others will be in the same boat soon, and a sane fallback like this will make the transition all that much more straight forward.

> The only downside to this is that it spawns an extra ruby process for the bundler check and that it's quite slow

If this is a concern, an alternative might be to just run `grep` against the associated `Gemfile.lock`:

```diff
- if test -e Gemfile; then
+ if test -e Gemfile && grep -q 'puma$' Gemfile.lock; then
```

**Comment by jeroenj** [comment]
That might even be better. Do you create a new PR or shall I update my PR? 👍

**Comment by rmm5t** [comment]
@jeroenj I submitted a separate PR #88 for @evanphx to consider as an alternative solution.

**Comment by jeroenj** [comment]
I just found a downside of not requiring puma in the Gemfile. If your app depends on a dependency that puma also has (e.g. rack) then you'll need to make sure that puma starts with the version your app depends on.

I have an old Rails 3 app that depends on rack 1.2 but rack 1.6 was installed for that given ruby version causing puma to load the latter and my app raising a warning that it can not load v1.2 since v1.6 already was loaded.

I still think this change is better than requiring puma to be in the Gemfile as the solution to that error is quite easy: either make sure that puma loads the same version of rack as your app depends on (by removing too recent versions or upgrading your app) or add puma to the Gemfile.
