### ISSUE TITLE
Apps fail to start when interactive shell automatically `cd`s to a different directory

### ISSUE THREAD

**Issue by lazyatom** [puma/puma-dev#74]
For odd and not terribly important reasons I have my zsh set up to `cd` into another directory when it starts up. It looks like this means that when puma-dev detects how to run `puma`, it's not actually in the app directory anymore and so it doesn't fine the `Gemfile` and tries to run `puma` directly instead.

As discussed, puma-dev could automatically `cd` back to the application directory during its boot up to avoid this (albeit very reasonable) assumption.

Thanks for your help debugging this, @evanphx!

**Comment by koenpunt** [comment]
You do this because you want to start in that directory in the terminal? If so, you can let your terminal handle that instead of the shell, then it won't no longer interfere with puma.

**Comment by lazyatom** [comment]
Yeah, that's very sensible. I think Evan just wanted me to document this so that `puma-dev` can be a bit smarter in the cases were this might be happening, since it's not obvious from the logging right now that this causes puma-dev to stumble.
