### ISSUE TITLE
puma-dev -install should warn if run under sudo

### ISSUE THREAD

**Issue by ticky** [puma/puma-dev#76]
Just spent an unfortunate amount of time debugging this when it was my own fault! :sweat_smile:

It'd be really helpful if `puma-dev` could assist with this!

What happens when `-install` is run under sudo;
1. Launch agent and `~/Library/Application\ Support/io.puma.dev` get created as root
2. Launch agent is then run as root, which creates the log file (in your user directory) as root, which then causes the launch agent to silently fail to launch if you run it as your user!

It might be helpful for `-cleanup` to be able to detect and help with this situation, too!

**Comment by evanphx** [comment]
Ah! Sure, I can detect that. Perhaps I should actually error out of `-install` is run under sudo entirely.

**Comment by ticky** [comment]
Yeah, that would make sense, too 😄

**Comment by attilagyorffy** [comment]
Relevant issue: https://github.com/puma/puma-dev/issues/80

**Comment by scottrobertson** [comment]
Just wasted an hour of my life because of this :D log file was owned by root. chowning that fixed it all.

**Comment by nonrational** [comment]
This is now released as part of v0.15.
