### ISSUE TITLE
"It works!" when loading .dev sites

### ISSUE THREAD

**Issue by olivierlacan** [puma/puma-dev#79]
I'm documenting this because I've run into this issue and I think I have a fix that perhaps could be something the puma-dev install checks for. 

It looks like for some reason [OS X enables httpd by default](http://serverfault.com/a/503175/160446). It runs on port 80 and intercepts requests that should be going to puma-dev.

I had to run `sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist` in order to remove `httpd` from launchctl. It appears that it was added to `/System/Library/LaunchDaemons/` on my machine around the time when I upgraded to El Capitan (OS X 10.11). 

`sudo lsof -i ':80'` confirms that the only thing listening on 80 after that was Google Chrome. `ps aux | grep httpd` no longer returned any results.

Not sure if anyone has run into similar issues but hopefully (if I'm not completely off base here) this should help others resolve this issue.

**Comment by kobaltz** [comment]
Year late to the game, for for those who also need `httpd` to run other things, you can edit `/etc/apache2/httpd.conf` and update the `Listen 80` to some other port like `8080`.  Restart apache `sudo apachectl restart` or reboot your machine.
