### ISSUE TITLE
ENV Support

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#8]
The other thing that pow did really well was `.powenv` which was just a file with environment variables that get passed to the running app.

```
$ cat .powenv
export SOME_VAR=some-value
```

**Comment by danrabinowitz** [comment]
Probably best done outside of puma/pow with something like https://github.com/bkeepers/dotenv

**Comment by silent-e** [comment]
This is breaking when the .env file doesn't use the `export` command in front of each variable.  The [dotenv readme](https://github.com/bkeepers/dotenv) indicates that's an option in case you want to `source` the files like you are doing in this commit.  However it is an option, not a requirement.

FYI

**Comment by zx1986** [comment]
Where should I put this file?
In my home directory? or app root?
