### ISSUE TITLE
Unable to install into system: writing cert.pem

### ISSUE THREAD

**Issue by kapowaz** [puma/puma-dev#80]
I’m still unable to install puma-dev, either via homebrew or the direct download by following the installation instructions. Using homebrew I get the same error mentioned in [this issue](https://github.com/puma/puma-dev/issues/46):

```
bdarlow@pinkman:~$ puma-dev -install
2016/08/10 16:54:26 Unable to install into system: exit status 1
```

Uninstalling puma-dev and downloading the binary, I get the following error:

```
bdarlow@pinkman:~$ puma-dev -install
2016/09/22 12:08:29 Unable to install into system: writing cert.pem: open /Users/bdarlow/Library/Application Support/io.puma.dev/cert.pem: permission denied
```

I was able to work around this issue by manually creating the folder `io.puma.dev` in `~/Library/Application Support`, but I assume there’s some issue with the install script where it’s failing to create this correctly.

This is running under Mac OS X El Capitan 10.11.6.

**Comment by evanphx** [comment]
@kapowaz I suspect that you ran `sudo puma-dev -install` at one point at the directories got created with the wrong perms. I need to add some checks into -install to better report what the situation is.
