### ISSUE TITLE
puma-dev doesn’t appear to run from launch daemon

### ISSUE THREAD

**Issue by kapowaz** [puma/puma-dev#81]
Following on from my issues discussed [here](https://github.com/puma/puma-dev/issues/80) (which may or may not be related to this problem), I was able to get puma-dev installed but found that DNS resolution wasn’t working. Further investigation with `ps aux` showed that the `puma-dev` process wasn’t running. Trying to run the launch daemon in `~/Library/LaunchAgents` with `launchctl -w` gave me a message that this service was already started. Stopping and restarting it made no difference.

This is running under Mac OS X El Capitan 10.11.6.

**Comment by evanphx** [comment]
@kapowaz What files are in `/etc/resolver` on that machine? Is there a `dev` file in there? What's in that file?
