### ISSUE TITLE
Couldn't get 0.3 to work

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#9]
0.3 doesn't work at all for me. El Cap 10.11.6.

I tried installing first, and got nothing. After a restart, manually running `puma-dev` gives me:

```
$ puma-dev
* Directory for apps: /Users/paulcampbell/.puma-dev
* Domains: pdev
* DNS Server port: 9253
* HTTP Server port: 9280
! Puma dev listening
```

But a visit to my linked site gets me a Connection refused:

```
$ curl http://organizer-tito.pdev
curl: (7) Failed to connect to organizer-tito.pdev port 80: Connection refused
```

Not sure what next debugging step should be.

**Comment by paulca** [comment]
This could be a `.pdev` / `.dev` issue as `.pdev` wasn't working for me on 0.2.

**Comment by paulca** [comment]
No, seems to be an 0.2 / 0.3 thing alright.

**Comment by evanphx** [comment]
In 0.3, you have to install it to have port 80 work. Otherwise use port
9280.

**Comment by evanphx** [comment]
Yeah, with 0.3 you have to use the launch agent to get port 80 usage. I suggest you try the new homebrew option!

First, run `puma-dev -uninstall`, then `sudo puma-dev -cleanup` to make sure your machine is all cleaned up.

Then `brew install puma/puma/puma-dev`. The output should give you some commands to run to finish the install.

I just realized that the installer probably only going to allow using `.pdev` right now, I'll update that shortly.

**Comment by paulca** [comment]
Heya,

All of this was great, and I certainly wouldn't have a problem with `.pdev`, port 80 is fine ... but when I try to connect to port 80 I was getting either timeouts or request.

I tried cleaning everything up, doing a fresh brew install. Running `puma-dev` I get:

```
$ puma-dev -pow
* Directory for apps: /Users/paulcampbell/.pow
* Domains: pdev
* DNS Server port: 9253
* HTTP Server port: 9280
! Puma dev listening
```

And curling in:

```
$ curl -vvvvvvv http://organizer-tito.dev
* Rebuilt URL to: http://organizer-tito.dev/
*   Trying 127.0.53.53...
```

Same for `.pdev`:

```
$ curl -vvvvvvv organizer-tito.dev
* Rebuilt URL to: organizer-tito.dev/
*   Trying 127.0.53.53...
```

Scratching my head. Since the behaviour is now the same whether `puma-dev` is running or not, I assum it's a `launchd` issue, so I'll see if I can debug that.

—P
