### ISSUE TITLE
How to configure the timeout for idle shutdown?

### ISSUE THREAD

**Issue by andrewhavens** [puma/puma-dev#91]
I find that the default idle shutdown timeout is too aggressive for me. I'd like to adjust it to be at least an hour or more. Is it currently possible to configure this timeout? If not, can you please point me in the right direction so that I can try to submit a pull request?

**Comment by evanphx** [comment]
You can add the `-timeout` flag to `puma-dev` to control how long it will wait.

**Comment by concept47** [comment]
@evanphx is there a way to put this in a configuration variable, or does it have to to be run from the command line all the time?

**Comment by harigopal** [comment]
@evanphx You can pass options along with the `-install` flag to set those for the background service.

```
$ puma-dev -install -timeout 180m
$ ps -e | grep puma-dev
/usr/local/Cellar/puma-dev/0.10/bin/puma-dev -launchd -dir ~/.puma-dev -d dev -timeout 3h0m0s
```

**Comment by concept47** [comment]
that just screwed things up for some reason. Now all I see in my logs is
`Error listening: accept tcp 0.0.0.0:0: accept: invalid argument`

**Comment by concept47** [comment]
Figured out the problem, I have Apache running on port 80 and had to run puma-dev on port 81. Thanks @harigopal
