### ISSUE TITLE
Puma-dev should be able to reach IPv6

### ISSUE THREAD

**Issue by joallard** [puma/puma-dev#96]
I can get my app on 0.0.0.0, localhost or `[::1]`, but not 127.0.0.1 by default. Any plan to address this in defaults?

**Comment by evanphx** [comment]
I'm not sure what you mean, could you tell me more about what you're seeing?

**Comment by joallard** [comment]
Okay, let me be a little clearer with an STR:

1. Start a `rails s`
2. Open `127.0.0.1` in the browser

Actual: Server can't be reached\
Expected: Server is reachable

To note that it is reachable on any of `0.0.0.0`, `localhost` or `[::1]`.

**Comment by joallard** [comment]
Oh wait, that's not the right bug for here. But what I mean is that when you call `myapp.dev`, puma-dev will try to reach `127.0.0.1` on which the server is not bound.

**Comment by evanphx** [comment]
I'm unsure why the address matters, you should be using the domain name anyway.

**Comment by formigarafa** [comment]
Macos' `hosts` file states that both `::1` and `127.0.0.1` translates to localhost. It seems that `rails` binds to localhost address with it seems macos translates to `::1` preferably.
When you try to access via puma-dev, it does not find se port open there and gives a 500.

Try commenting the line below in the `/etc/hosts` file:
`# ::1             localhost`

After restart rails it should come back to life for puma-dev.
