### ISSUE TITLE
Puma not installed

### ISSUE THREAD

**Issue by magicalbanana** [puma/puma-dev#98]
I keep getting this error:

```
foo_app[26765]: bundler: command not found: puma
foo_app[26765]: Install missing gem executables with `bundle install`
```

**Comment by evanphx** [comment]
You need to include puma into your Gemfile.

**Comment by koenpunt** [comment]
I have the same issue, but actually have `puma` in my Gemfile: 

```
$ grep puma Gemfile.lock
    capistrano-pumactl (0.0.1)
    puma (3.6.0)
  capistrano-pumactl
  puma
```

**Comment by koenpunt** [comment]
Might this be related to the fact that I'm using rbenv? And that maybe the environment is not correctly inherited?

**Comment by koenpunt** [comment]
Oh nevermind, had a `.env` file with the values from the staging environment.
