### ISSUE TITLE
If public contains directory matching route path, it returns a directory index

### ISSUE THREAD

**Issue by waynerobinson** [puma/puma-dev#99]
If something like `/public/admin` exists and there is a route for `admin` (alone), then puma-dev will serve a directory index (one it creates itself, there is no index.html file), instead of the route.

puma-dev should probably check to see if the path is a directory before choosing to serve the file itself.

**Comment by evanphx** [comment]
Everything in public  is handled by puma-dev strictly. Are you saying that your app has a route for `public/admin`?

**Comment by waynerobinson** [comment]
No, the route is for `/admin`. 

But there is also the directory `/public/admin` for some global assets managed outside of sprockets.

When puma-dev sees the `/admin` URL, it finds there is a `/public/admin` directory and decides it should handle serving that itself. Even though there is no `index.html` or similar — it just serves a directory listing it constructs itself.

**Comment by waynerobinson** [comment]
I'm not sure how to submit a PR but it seems the issue is with https://github.com/puma/puma-dev/blob/80d569425853b7aaf10a91b47513fa7d80d67741/dev/http.go#L187

Files and directories both return valid responses to `os.Stat(path)`. If this can check to see if the path is actually a file before responding statically to it, that would solve this issue.

**Comment by waynerobinson** [comment]
Any chance of getting a new binary/Brew release with this change in it?

Cheers
:)

**Comment by evanphx** [comment]
So sorry about the delay, new release out now.

**Comment by waynerobinson** [comment]
Thanks for this! Works like a charm! 👍
